'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const core=path.join(__dirname,'../site/nu545/exam7/js/core');
function disk(){return {data:new Map(),events:[],tabs:[],blocked:false,flush(){let guard=0;while(this.events.length){assert.ok(++guard<1000,'storage event convergence');const [source,key,newValue]=this.events.shift();this.tabs.forEach(t=>{if(t!==source)t.listener?.({key,newValue});});}}};}
function tab(d=disk(),initial){let now=100000;const t={};d.tabs.push(t);const DateFake=class extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};
const items=Array.from({length:30},(_,i)=>({id:'nu545-e7-p-'+i,rootId:'root'+i,c:i<2?'c1':'c'+i,t:'mc',pool:'practice',q:'Q'+i,o:[{t:'yes',ok:true},{t:'no',ok:false}]}));
const L={CONFIG:{id:'nu545-exam7'},ITEMS:items,CONCEPTS:Object.fromEntries(items.map(i=>[i.c,{mastery:true}])),CASES:[],BOSSES:[],FORMS:{}};
const ctx=vm.createContext({L,Date:DateFake,console,localStorage:{getItem(k){if(d.blocked)throw Error('blocked');return d.data.get(k)||null;},setItem(k,v){if(d.blocked)throw Error('blocked');d.data.set(k,v);d.events.push([t,k,v]);}},addEventListener(type,fn){if(type==='storage')t.listener=fn;}});
if(initial)d.data.set('nu545-exam7-progress-v1',initial);
for(const f of ['store.js','engine.js'])vm.runInContext(fs.readFileSync(path.join(core,f),'utf8'),ctx,{filename:f});
return Object.assign(t,{L,d,advance(ms){now+=ms;},create(type='practice',ids=['nu545-e7-p-0'],extra={}){return L.engine.createRun({type,title:'test',itemIds:ids,...extra});},answer(id,index=0,response=0,conf='m',hint=false){return L.engine.check(id,L.engine.run(id).items[index].occurrenceId,response,conf,hint);}});}
test('first checks are immutable, correction is separate and all valid modes share history',()=>{const t=tab();for(const mode of ['practice','review','case','boss','mock']){const id=t.create(mode);assert.equal(t.answer(id).first,true);assert.equal(t.answer(id,0,1,'h').first,false);assert.equal(t.L.engine.run(id).responses[t.L.engine.run(id).items[0].occurrenceId].correct,true);t.L.engine.correction(id,t.L.engine.run(id).items[0].occurrenceId,1,'h');assert.equal(t.L.engine.run(id).corrections.length,1);}assert.equal(t.L.store.load().attempts.length,5);});
test('confidence and actual MC response are strictly validated',()=>{const t=tab(),id=t.create();for(const r of [null,undefined,'', '0',[],{},-1,2,NaN])assert.equal(t.L.engine.check(id,t.L.engine.run(id).items[0].occurrenceId,r,'m').first,false);for(const c of ['',null,'medium',{},0])assert.equal(t.answer(id,0,0,c).first,false);assert.equal(t.L.store.load().attempts.length,0);assert.equal(t.answer(id).first,true);});
test('mastery needs distinct roots, no hints, latest confidence medium or high, and survives a future miss',()=>{const t=tab();for(let k=0;k<2;k++)t.answer(t.create('mock'));assert.equal(t.L.engine.stats().c1.mastered,false);t.answer(t.create('mock',['nu545-e7-p-1']),0,0,'m',true);assert.equal(t.L.engine.stats().c1.mastered,false);t.answer(t.create('boss',['nu545-e7-p-0']));t.answer(t.create('review',['nu545-e7-p-1']));assert.equal(t.L.engine.stats().c1.mastered,true);t.answer(t.create('mock'),0,1,'h');const s=t.L.engine.stats().c1;assert.equal(s.mastered,true);assert.equal(s.misconception,true);assert.equal(s.due,true);assert.equal(s.reviewReason,'misconception');assert.ok(t.L.engine.reviewItems().some(i=>i.c==='c1'));});
test('low confidence final answer cannot earn mastery',()=>{const t=tab();t.answer(t.create('mock'));t.answer(t.create('mock',['nu545-e7-p-1']),0,0,'l');assert.equal(t.L.engine.stats().c1.mastered,false);});
test('teach and explicitly ineligible source items never earn mastery',()=>{const t=tab();t.L.ITEMS[0].eligible=false;t.L.ITEMS[1].eligible=false;t.answer(t.create('boss'));t.answer(t.create('boss',['nu545-e7-p-1']));assert.equal(t.L.engine.stats().c1.mastered,false);t.L.CASES=[{id:'case1',c:'c1',t:'teach',model:'x',rubric:['x']}];const id=t.create('case',['case1']);assert.equal(t.answer(id,0,{text:'My comparison',self:'complete'}).first,true);assert.equal(t.L.store.load().attempts.at(-1).eligible,false);});
test('retry distance is exact: miss +2, low confidence +4, with unique first responses',()=>{for(const [response,conf,gap] of [[1,'h',2],[0,'l',4]]){const t=tab(),id=t.create('practice',t.L.ITEMS.slice(0,8).map(i=>i.id));t.answer(id,0,response,conf);let r=t.L.engine.run(id),retry=r.items.find(i=>i.retry);assert.equal(r.items.indexOf(retry),gap+1);assert.equal(t.L.engine.check(id,retry.occurrenceId,0,'m').first,false);for(let j=1;j<=gap;j++)t.answer(id,j);assert.equal(t.L.engine.check(id,retry.occurrenceId,0,'m').first,true);r=t.L.engine.run(id);assert.equal(r.responses[r.items[0].occurrenceId].correct,response===0);assert.notEqual(retry.occurrenceId,r.items[0].occurrenceId);}});
test('short practice queues get bridges rather than immediate retry; mocks never retry',()=>{const t=tab(),id=t.create();t.answer(id,0,1,'m');const r=t.L.engine.run(id);assert.equal(r.items.length,4);assert.equal(r.items[3].retry,true);const m=t.create('mock');t.answer(m,0,1,'l');assert.equal(t.L.engine.run(m).items.length,1);});
test('drafts and full saved snapshots survive reload and content revision',()=>{const t=tab(),id=t.create('mock',['nu545-e7-p-0','nu545-e7-p-1']);t.answer(id);const occ=t.L.engine.run(id).items[1].occurrenceId;t.L.engine.saveDraft(id,occ,0,'h');const b=tab(t.d);b.L.ITEMS[0].q='revised';b.L.ITEMS[1].o[0].ok=false;b.L.ITEMS[1].o[1].ok=true;assert.equal(b.L.engine.run(id).items[0].q,'Q0');assert.equal(b.L.engine.run(id).drafts[occ].confidence,'h');assert.equal(b.L.engine.check(id,occ,0,'h').ok,true);assert.equal(b.L.engine.run(id).items[1].o[0].ok,true);});
test('elapsed mock timer persists across reload, expires without accepting stale answers, blanks score zero',()=>{const t=tab(),id=t.create('mock',['nu545-e7-p-0','nu545-e7-p-1'],{durationSec:5});t.answer(id);const b=tab(t.d);b.advance(5000);assert.equal(b.answer(id,1).first,false);assert.equal(b.L.engine.run(id).status,'completed');assert.equal(Object.keys(b.L.engine.run(id).responses).length,1);assert.equal(b.L.store.load().attempts.length,1);assert.equal(b.L.engine.activeRuns().length,0);});
test('early or short Boss cannot establish best; full 25 item Boss can',()=>{const t=tab();const ids=t.L.ITEMS.slice(0,25).map(i=>i.id),early=t.create('boss',ids);t.answer(early);t.L.engine.finishRun(early,true);assert.equal(t.L.engine.bossBest(),null);const short=t.create('boss');t.answer(short);t.L.engine.finishRun(short);assert.equal(t.L.engine.bossBest(),null);const full=t.create('boss',ids);for(let i=0;i<25;i++)t.answer(full,i,i===24?1:0);t.L.engine.finishRun(full);assert.equal(t.L.engine.bossBest(),24/25);});
test('merge imports preserve local checks, snapshots, newer drafts, corrections, mastery and deduplicate history',()=>{const t=tab(),id=t.create('mock',['nu545-e7-p-0','nu545-e7-p-1']);t.answer(id);const data=JSON.parse(t.L.store.exportJSON());const occ=data.state.runs[id].items[0].occurrenceId;data.state.runs[id].responses[occ]={response:1,confidence:'h',correct:false,checkedAt:999999,assisted:false};data.state.runs[id].items[0].q='rewritten';Object.assign(data.state.attempts[0],{response:1,confidence:'h',correct:false,timestamp:999999});const other=data.state.runs[id].items[1].occurrenceId;data.state.runs[id].drafts[other]={response:1,confidence:'l',updatedAt:999999};assert.equal(t.L.store.importText(JSON.stringify(data)).ok,true);assert.equal(t.L.engine.run(id).responses[occ].correct,true);assert.equal(t.L.engine.run(id).items[0].q,'Q0');assert.equal(t.L.engine.run(id).drafts[other].response,1);assert.equal(t.L.store.load().attempts.length,1);assert.equal(t.L.store.importText(JSON.stringify(data)).ok,true);assert.equal(t.L.store.load().attempts.length,1);});
test('wrong course, future schema, malformed imports leave state intact',()=>{const t=tab();t.answer(t.create('mock'));const before=t.L.store.exportJSON();for(const data of ['bad',JSON.stringify({app:'nu518-exam2',schema:1,state:{}}),JSON.stringify({app:'nu545-exam7',schema:2,state:{}}),JSON.stringify({app:'nu545-exam7',schema:1,attempts:[]})]){assert.equal(t.L.store.importText(data).ok,false);assert.equal(t.L.store.exportJSON(),before);}});
test('corrupt/future disk data is preserved byte-for-byte and recovery warning is exposed',()=>{for(const raw of ['{bad',JSON.stringify({app:'nu545-exam7',schema:3})]){const t=tab(disk(),raw);t.create();assert.equal(t.d.data.get(t.L.store.KEY),raw);assert.ok([...t.d.data.keys()].some(k=>k.includes('recovery')));assert.equal(t.L.store.ok(),false);assert.ok(t.L.store.warning());}});
test('blocked storage keeps usable in-memory progress and exports it',()=>{const d=disk();d.blocked=true;const t=tab(d),id=t.create('mock');assert.equal(t.answer(id).first,true);assert.equal(t.L.store.ok(),false);assert.equal(JSON.parse(t.L.store.exportJSON()).state.attempts.length,1);});
test('cross-tab stale memory writes and storage events merge rather than erase attempts/drafts',()=>{const d=disk(),a=tab(d),b=tab(d);a.L.store.load();b.L.store.load();const ai=a.create('mock'),bi=b.create('mock');a.answer(ai);b.answer(bi);d.flush();assert.equal(a.L.store.load().attempts.length,2);assert.equal(b.L.store.load().attempts.length,2);assert.equal(Object.keys(JSON.parse(d.data.get(a.L.store.KEY)).runs).length,2);const occurrence=a.L.engine.run(ai).items[0].occurrenceId;assert.equal(b.L.engine.check(ai,occurrence,1,'h').first,false);d.flush();assert.equal(a.L.store.load().attempts.length,2);});
test('listener repairs true overwritten concurrent writes using cached union',()=>{const d=disk(),a=tab(d),b=tab(d);a.L.store.load();b.L.store.load();a.answer(a.create('mock'));const savedA=d.data.get(a.L.store.KEY);d.data.delete(a.L.store.KEY);b.answer(b.create('mock'));const savedB=d.data.get(b.L.store.KEY);a.listener({key:a.L.store.KEY,newValue:savedB});b.listener({key:b.L.store.KEY,newValue:savedA});d.flush();assert.equal(JSON.parse(d.data.get(a.L.store.KEY)).attempts.length,2);});
test('history is not truncated; subscriptions notify and unsubscribe',()=>{const t=tab();let n=0;const off=t.L.store.subscribe(()=>n++);t.create('mock');assert.ok(n);off();const before=n;t.create('mock');assert.equal(n,before);const s=t.L.store.load(),template={id:'a',itemId:'i',rootId:'r',conceptId:'c1',mode:'mock',response:0,confidence:'m',correct:true,assisted:false,timestamp:1,snapshot:{id:'i',rootId:'r',c:'c1',t:'mc',o:[{t:'yes',ok:true},{t:'no',ok:false}]},eligible:true};for(let i=0;i<6100;i++)s.attempts.push({...template,id:'a'+i,timestamp:i});t.L.store.save();assert.equal(tab(t.d).L.store.load().attempts.length,6100);});
test('simultaneous same-occurrence checks converge to one scored attempt matching first response',()=>{const d=disk(),a=tab(d),id=a.create('mock'),b=tab(d);b.L.store.load();const unchecked=d.data.get(a.L.store.KEY);a.answer(id,0,1,'h');const av=d.data.get(a.L.store.KEY);d.data.set(a.L.store.KEY,unchecked);b.answer(id,0,0,'m');const bv=d.data.get(a.L.store.KEY);a.listener({key:a.L.store.KEY,newValue:bv});b.listener({key:b.L.store.KEY,newValue:av});d.flush();const state=JSON.parse(d.data.get(a.L.store.KEY)),r=state.runs[id],occ=r.items[0].occurrenceId;assert.equal(state.attempts.length,1);assert.equal(state.attempts[0].response,r.responses[occ].response);assert.equal(state.attempts[0].correct,r.responses[occ].correct);assert.equal(a.L.store.load().attempts.length,1);assert.equal(b.L.store.load().attempts.length,1);});
test('import merges newer draft and separate correction records while preserving checked initial response',()=>{const t=tab(),id=t.create('mock',['nu545-e7-p-0','nu545-e7-p-1']);t.answer(id);let r=t.L.engine.run(id);t.L.engine.saveDraft(id,r.items[1].occurrenceId,1,'l');const incoming=JSON.parse(t.L.store.exportJSON());t.advance(10);t.L.engine.saveDraft(id,r.items[1].occurrenceId,0,'h');incoming.state.runs[id].corrections.push({id:'imported-correction',occurrenceId:r.items[0].occurrenceId,response:1,confidence:'h',correct:false,timestamp:100002});assert.equal(t.L.store.importText(JSON.stringify(incoming)).ok,true);r=t.L.engine.run(id);assert.equal(r.drafts[r.items[1].occurrenceId].response,0);assert.equal(r.corrections.length,1);assert.equal(r.responses[r.items[0].occurrenceId].correct,true);});
test('malformed saved keys, unsafe fields, draft confidence and run responses reject imports',()=>{const t=tab(),id=t.create('mock');t.answer(id);const original=t.L.store.exportJSON();for(const mutate of [s=>s.runs[id].items[0].o[1].ok=true,s=>s.runs[id].responses[s.runs[id].items[0].occurrenceId].response='0',s=>s.runs[id].drafts[s.runs[id].items[0].occurrenceId]={response:0,confidence:'x',updatedAt:1},s=>Object.defineProperty(s.settings,'__proto__',{value:{polluted:true},enumerable:true})]){const value=JSON.parse(original);mutate(value.state);assert.equal(t.L.store.importText(JSON.stringify(value)).ok,false);assert.equal(t.L.store.exportJSON(),original);}});
test('manual mock submission may complete with blanks, and initial drafts never count as checked answers',()=>{const t=tab(),id=t.create('mock',['nu545-e7-p-0','nu545-e7-p-1']);t.answer(id);const occ=t.L.engine.run(id).items[1].occurrenceId;t.L.engine.saveDraft(id,occ,0,'h');t.L.engine.finishRun(id);assert.equal(t.L.engine.run(id).status,'completed');assert.equal(t.L.store.load().attempts.length,1);assert.equal(Object.keys(t.L.engine.run(id).responses).length,1);});
test('storage quota failure after initial load retains attempts and reports memory-only persistence',()=>{const t=tab(),id=t.create('mock');t.d.blocked=true;assert.equal(t.answer(id).first,true);assert.equal(t.L.store.ok(),false);assert.equal(JSON.parse(t.L.store.exportJSON()).state.attempts.length,1);});

test('hint survives changing draft and reload; engine reads durable assistance',()=>{const t=tab(),id=t.create('mock',['nu545-e7-p-0','nu545-e7-p-1']),occ=t.L.engine.run(id).items[0].occurrenceId;t.L.engine.saveDraft(id,occ,0,'m');t.L.store.transact(s=>s.runs[id].drafts[occ].assisted=true);t.advance(1);t.L.engine.saveDraft(id,occ,0,'h');const b=tab(t.d);b.L.engine.check(id,occ,0,'h',false);b.answer(id,1);assert.equal(b.L.store.load().attempts[0].assisted,true);assert.equal(b.L.engine.stats().c1.mastered,false);});
test('discarded simultaneous success cannot preserve false mastery',()=>{const d=disk(),a=tab(d);a.answer(a.create('mock'));const id=a.create('mock',['nu545-e7-p-1']),b=tab(d);b.L.store.load();const common=d.data.get(a.L.store.KEY);a.advance(2);a.answer(id,0,1,'h');const av=d.data.get(a.L.store.KEY);d.data.set(a.L.store.KEY,common);b.advance(3);b.answer(id,0,0,'h');const bv=d.data.get(b.L.store.KEY);a.listener({key:a.L.store.KEY,newValue:bv});b.listener({key:b.L.store.KEY,newValue:av});d.flush();assert.deepEqual(Array.from(a.L.store.load().attempts,x=>x.correct),[true,false]);assert.equal(a.L.engine.stats().c1.mastered,false);assert.equal(b.L.engine.stats().c1.mastered,false);});
test('older note import and no-op progress reads preserve new work without disk writes',()=>{const t=tab();t.L.store.transact(s=>s.notes.ch21={text:'old',updatedAt:1});const backup=t.L.store.exportJSON();t.L.store.transact(s=>s.notes.ch21={text:'new',updatedAt:2});assert.equal(t.L.store.importText(backup).ok,true);assert.equal(t.L.store.load().notes.ch21.text,'new');const writes=t.d.events.length;t.L.engine.stats();t.L.engine.activeRuns();assert.equal(t.d.events.length,writes);});
test('case text is required and saved parent scenario survives content removal',()=>{const t=tab();t.L.CASES=[{id:'case1',stem:'Original patient story',items:[{id:'teach1',c:'c1',t:'teach',model:'x',rubric:['x']}]}];const id=t.create('case',['teach1']);assert.equal(t.answer(id,0,{text:' ',self:'complete'}).first,false);assert.equal(t.answer(id,0,{text:'My answer',self:'complete'}).first,true);t.L.CASES=[];assert.equal(t.L.engine.run(id).items[0].caseStem,'Original patient story');assert.equal(t.L.store.load().attempts.at(-1).eligible,false);});
test('inconsistent keys, attempt/run relationships and markup identifiers reject import',()=>{const t=tab();t.answer(t.create('mock'),0,1);const base=JSON.parse(t.L.store.exportJSON());for(let n=0;n<3;n++){const x=JSON.parse(JSON.stringify(base)),r=Object.values(x.state.runs)[0],occ=r.items[0].occurrenceId;if(n===0){x.state.attempts[0].correct=true;r.responses[occ].correct=true;}if(n===1)x.state.attempts[0].conceptId='other';if(n===2){r.items[0].occurrenceId='x\"><img src=x>';r.responses[r.items[0].occurrenceId]=r.responses[occ];delete r.responses[occ];}assert.equal(t.L.store.importText(JSON.stringify(x)).ok,false);}});
