'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const base=path.resolve(__dirname,'../site/nu545/exam7'),ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(base+'/js/data/course.js','utf8'),ctx);vm.runInContext(fs.readFileSync(base+'/js/data/media.js','utf8'),ctx);const L=ctx.L;
test('exam identity, original pool, coverage and distinct forms',()=>{assert.equal(L.CONFIG.id,'nu545-exam7');assert.equal(L.ITEMS.length,120);assert.equal(new Set(L.ITEMS.map(x=>x.id)).size,120);assert.equal(new Set(L.ITEMS.map(x=>x.q)).size,120);assert.equal(L.SECTIONS.length,10);assert.equal(L.COVERAGE.prompts.length,51);assert.equal(L.COVERAGE.components.components.length,166);assert.equal(L.CASES.length,10);assert.equal(L.BOSSES[0].refs.length,25);const ids=Object.values(L.FORMS).flat();assert.equal(ids.length,60);assert.equal(new Set(ids).size,60);for(const f of Object.values(L.FORMS)){assert.equal(f.length,20);for(const s of L.SECTIONS)assert.equal(f.filter(id=>L.ITEMS.find(i=>i.id===id).sec===s.id).length,2);}});
test('every item carries supported key, option reasons, original identity, source and DNA',()=>{for(const i of L.ITEMS){assert.equal(i.o.filter(o=>o.ok).length,1,i.id);assert.equal(i.o.length,4);assert.ok(i.explain&&i.evidenceExcerpt&&i.editorialRevision&&i.decision,i.id);assert.ok(i.reviewer.includes('separate'),i.id);assert.ok(i.o.every(o=>o.t&&o.w&&!o.w.includes('does not match the')),i.id);for(const r of i.s)assert.ok(L.SOURCES[r]&&L.SOURCE_HTML[r],i.id+' '+r);assert.ok(!i.q.includes('4 mg')&&!i.q.includes('4%'));}});
test('every eligible concept has two distinct practice roots and guide teaching',()=>{for(const [c,v]of Object.entries(L.CONCEPTS)){assert.ok(new Set(L.ITEMS.filter(i=>i.c===c&&i.pool==='practice').map(i=>i.rootId)).size>=2,c);assert.ok(L.GUIDE[v.sec].some(g=>g.c.includes(c)),c);}for(const c of L.CASES){assert.equal(c.items[0].eligible,false);assert.ok(c.items[0].model&&c.items[0].rubric.length);}});
test('ten playable chapter films with local references, time maps and valid caption order',()=>{assert.equal(L.MEDIA_FILMS.length,10);for(const s of L.SECTIONS){const f=L.MEDIA_FILMS.find(f=>f.chapters.includes(s.n));assert.ok(f);for(const key of ['src','poster','captions','transcriptSrc','animationSource'])assert.ok(fs.statSync(path.join(base,f[key])).size>0);for(const r of f.sources)assert.ok(L.SOURCES[r],r);const probe=JSON.parse(cp.execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',path.join(base,f.src)],{encoding:'utf8'}));assert.ok(probe.streams.some(x=>x.codec_name==='h264'&&x.width===1280&&x.height===720));assert.ok(probe.streams.some(x=>x.codec_name==='aac'));assert.ok(Math.abs(+probe.format.duration-f.duration)<.2);let last=-1;for(const stage of f.stages){assert.ok(stage.start>last&&stage.start<f.duration);last=stage.start;}const stamp=s=>s.split(':').reduce((a,b)=>a*60+Number(b),0);let end=0;for(const m of fs.readFileSync(path.join(base,f.captions),'utf8').matchAll(/(\d\d:\d\d:\d\d\.\d{3}) --> (\d\d:\d\d:\d\d\.\d{3})/g)){assert.ok(stamp(m[1])>=end-.02);assert.ok(stamp(m[2])>stamp(m[1])&&stamp(m[2])<=f.duration+.05);end=stamp(m[2]);}assert.ok(end>f.duration-2);}});
test('accepted feedback and separate storage survive reuse',()=>{const css=fs.readFileSync(base+'/css/app.css','utf8');assert.ok(css.includes('#4cd07d')&&css.includes('#ff6b6b'));const store=fs.readFileSync(base+'/js/core/store.js','utf8');assert.ok(store.includes('nu545-exam7-progress-v1'));assert.ok(!store.includes('nu545-exam3'));const app=fs.readFileSync(base+'/js/app.js','utf8');assert.ok(app.includes("type==='mock'?1800"));assert.ok(app.indexOf('${movie(s.n)}')<app.indexOf('<div class="tabs">${L.SECTIONS'));});

test('finished mock countdown stays at its recorded completion time; active expiry still closes the run',()=>{
  const app=fs.readFileSync(path.join(base,'js/app.js'),'utf8');
  const tick=app.slice(app.indexOf('function tick(){'),app.indexOf('\nwindow.addEventListener'));
  let now=500000,closed=0,routed=0;
  const run={id:'qa-timing',startedAt:100000,durationSec:1800,status:'completed',completedAt:160000};
  const el={dataset:{runTimer:'qa-timing'},textContent:''};
  const context={document:{querySelector:()=>el},Date:{now:()=>now},E:{run:()=>run,finishRun:()=>closed++},route:()=>routed++};
  vm.createContext(context);vm.runInContext(tick,context);context.tick();
  assert.equal(el.textContent,'29:00 remaining when finished');
  now+=86400000;context.tick();assert.equal(el.textContent,'29:00 remaining when finished');assert.equal(closed,0);
  run.status='active';context.tick();assert.equal(el.textContent,'0:00 remaining');assert.equal(closed,1);assert.equal(routed,1);
});
