"""Build film metadata from completed, local Clear audio alignment and licensed art."""
from pathlib import Path
import hashlib,json
HERE=Path(__file__).resolve().parent;MEDIA=HERE.parent;ROOT=MEDIA.parent
figures=[
 dict(file='hematopoiesis.jpg',title='Hematopoietic cell lineages',chapters=[28,30],credit='OpenStax, Anatomy and Physiology, version 8.25 (2016)',url='https://commons.wikimedia.org/wiki/File:0337_Hematopoiesis_new.jpg',license='CC BY 4.0',licenseUrl='https://creativecommons.org/licenses/by/4.0/',alt='Original scholarly lineage tree with erythrocyte and macrophage artwork.',alterations='Original preserved. Film uses resized/cropped lineage, erythrocyte and macrophage images; reversible cell deformation, production, clearance and schematic transport markers added.'),
 dict(file='hemostasis.jpg',title='Normal vessel repair and hemostasis',chapters=[28,29,30],credit='OpenStax College, Anatomy and Physiology (2013), 1909 Blood Clotting; part (a) credit Kevin MacKenzie',url='https://commons.wikimedia.org/wiki/File:1909_Blood_Clotting.jpg',license='CC BY 3.0',licenseUrl='https://creativecommons.org/licenses/by/3.0/',alt='Original hemostasis figure, including the vessel cross-section used as a reference in the films.',alterations='Original preserved. The vessel segment is cropped/rescaled. Schematic cell motion, intravascular fibrin accumulation, impaired flow and consumption markers are added; DIC overlays are distinguished from the original normal-repair figure.'),
 dict(file='sickle.svg',title='Sickle erythrocyte',chapters=[30],credit='Database Center for Life Science (DBCLS), Togo picture gallery (2024), DOI 10.7875/togopic.2024.219',url='https://commons.wikimedia.org/wiki/File:202410_Sckle_Cell.svg',license='CC BY 4.0',licenseUrl='https://creativecommons.org/licenses/by/4.0/',alt='Original DBCLS illustration of sickle erythrocytes.',alterations='Original SVG preserved. Rendered to sickle.png with CairoSVG, then cell crop/rescale and schematic motion added.'),
 dict(file='heart.jpg',title='Internal anatomy of the heart',chapters=[31,32],credit='OpenStax College, Anatomy and Physiology (2013)',url='https://commons.wikimedia.org/wiki/File:2008_Internal_Anatomy_of_the_HeartN.jpg',license='CC BY 3.0',licenseUrl='https://creativecommons.org/licenses/by/3.0/',alt='Original OpenStax anterior heart cutaway with chambers, valves and vessels labeled.',alterations='Original preserved. Film uses an anatomical crop/rescale, schematic flow markers and valve-state marks, and relative volume markers. Posterior aortic flow is hidden where the anterior pulmonary trunk overlies it. No image generation or invented organ anatomy.'),
 dict(file='vsd.jpg',title='Normal heart and ventricular septal defect',chapters=[33],credit='CDC, National Center on Birth Defects and Developmental Disabilities',url='https://www.cdc.gov/heart-defects/about/ventricular-septal-defect.html',license='U.S. public domain, absent a stated third-party copyright restriction',licenseUrl='https://www.cdc.gov/other/agencymaterials.html',alt='CDC comparison of a normal heart and VSD, with an arrow crossing the ventricular septum.',alterations='Original preserved. Film crops/rescales the paired anatomy and adds schematic left-to-right and pulmonary flow. Use does not imply endorsement by CDC, HHS, or the U.S. Government.')
]
for f in figures:
 f['src']='media/figures/'+f['file'];f['sha256']=hashlib.sha256((ROOT/f['src']).read_bytes()).hexdigest();f['licenseVerified']='2026-10-02'
 if f['file']=='sickle.svg':f['licenseVerificationUrl']='https://dbcls.rois.ac.jp/ja/2023/11/30/post1.html';f['licenseNote']='Commons review is pending; the DBCLS institutional announcement independently states CC BY 4.0 for TogoTV illustrations.'
(MEDIA/'figures.json').write_text(json.dumps(figures,indent=2)+'\n')
films=[]
for ch in range(28,34):
 t=json.loads((HERE/f'ch{ch}-timing.json').read_text());credit='; '.join(f['credit']+' ('+f['license']+')' for f in figures if ch in f['chapters'])
 films.append(dict(title=t['title'],chapters=[ch],src=f'media/ch{ch}-academic.mp4',poster=f'media/ch{ch}-academic-poster.jpg',captions=f'media/ch{ch}-academic.vtt',transcriptSrc=f'media/ch{ch}-academic.txt',sources=t['sources'],stages=t['stages'],voice='AI Voice Generator · Clear',duration=t['duration'],figureCredit=credit+'. Cropped/rescaled; schematic time, scale and process overlays. Originals and alterations are disclosed below.',animationSource='media/animation-source/render_chapters.py',scriptSrc='media/animation-source/chapter-film-scripts.json',timingSrc=f'media/animation-source/ch{ch}-timing.json',attributionSrc='media/ATTRIBUTION.md',status='Packet-supported mechanism; source limitations remain visible'))
academic=[]
for f in figures:
 for ch in f['chapters']:academic.append(dict(chapter=ch,title=f['title'],src=f['src'],alt=f['alt'],notice='This figure supports visualization. Tested facts come only from the assigned packet. '+f['alterations'],credit=f['credit'],url=f['url'],license=f['license'],licenseUrl=f['licenseUrl'],sha256=f['sha256']))
(ROOT/'js/data/media.js').write_text('(function(L){Object.assign(L,'+json.dumps(dict(MEDIA_FILMS=films,MEDIA_SAMPLE=None,ACADEMIC_FIGURES=academic),separators=(',',':'))+');})((typeof window!=="undefined"?window:globalThis).L);\n')
text='# Scholarly figure and narration attribution\n\nChecked October 2, 2026. External art is a visual aid and never expands the graded factual pool. Original files are preserved, with SHA-256 receipts in figures.json. Animation time, cell count, dimensions, pressures and volumes are schematic; they are not measured clinical values. No endorsement is implied.\n\n'
for f in figures:
 text+=('Institutional license confirmation: '+f['licenseVerificationUrl']+'. '+f['licenseNote']+'\n\n' if f.get('licenseVerificationUrl') else '')+f"## {f['title']}\n\n{f['credit']}. [Source]({f['url']}); [license or agency reuse policy]({f['licenseUrl']}) ({f['license']}).\n\nAlterations: {f['alterations']}\n\nOriginal: figures/{f['file']}. SHA-256: {f['sha256']}.\n\n"
text+='## Narration and editable source\n\nSix original scripts were checked against the exact course slides cited in each film. AI Voice Generator, Clear, supplied all completed narration. The signed provider download URLs and private projects are excluded. No subscription purchase or upgrade was made. The shared account showed 30K characters/month and sufficient existing quota; observed usage rose from 3K to 8K while concurrent exam work also used the account. These figures are observations, not itemized cost attribution. Playback is bundled locally and costs $0 per use.\n\nThe animation-source folder contains scripts, actual word/stage timings, caption alignment, the Pillow/FFmpeg renderer and manifest builder. Local Whisper timing is an alignment aid; captions retain the written script rather than replacing medical terms with recognition output. Narration and schematic overlays do not award mastery.\n'
(MEDIA/'ATTRIBUTION.md').write_text(text)
print('6 film entries; 5 original artworks; 9 chapter-specific figure references')
