# Source-depth teaching expansion, maintained separately from the item bank.
from pathlib import Path
import json,html,re
P=Path(__file__).resolve().parent; ROOT=P.parents[3];OUT=ROOT/'site/nu545/exam7';DOC=P.parent
esc=html.escape
D=[]
def card(ch,title,cols,rows,refs):D.append(dict(ch=ch,h=title,html='<table><thead><tr>'+''.join('<th>'+esc(c)+'</th>' for c in cols)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(c)+'</td>' for c in r)+'</tr>' for r in rows)+'</tbody></table>',refs=refs))
card(48,'Adult shock: follow the initiating failure',['Type','Mechanism and findings','Management in the supplied deck'],[
('Cardiogenic','Pump dysfunction despite adequate volume. Reduced output activates fluid retention, vasoconstriction and tachycardia, further burdening the heart. Chest pain, dyspnea, hypotension, jugular venous distention and dysrhythmias may occur.','Cardiac and hemodynamic support; selected coronary reperfusion interventions and assist devices. Treatment follows the cause, with continuous monitoring.'),
('Hypovolemic','Loss of blood, plasma or interstitial fluid reduces circulating volume. Thirst, poor skin turgor, oliguria, low preload and rapid heart rate accompany compensatory vasoconstriction.','Control hemorrhage and replace fluid.'),
('Neurogenic','Imbalanced autonomic stimulation causes vasodilation, low vascular resistance and relative hypovolemia. Blood volume can be unchanged while vascular capacity expands. Bradycardia is a supplied discriminator.','The adult slide only says to decrease pain. A complete management sequence is a source gap.'),
('Anaphylactic','Allergen-triggered immune inflammation causes vasodilation and fluid shift to interstitium. Dyspnea, edema, hives, itching and gastrointestinal symptoms occur.','Remove antigen where possible. Epinephrine supports vasoconstriction and reverses airway constriction. Volume expanders address relative hypovolemia; antihistamines/steroids address inflammatory features. These are course categories, not a complete dosing protocol.'),
('Septic','Infection activates inflammatory, complement, coagulation and kinin pathways. Vasodilation produces low resistance and maldistributed tissue perfusion.','Obtain cultures, assess lactate, give antibiotics, fluid support and vasopressors. The deck names norepinephrine. Do not extrapolate exact bedside protocols beyond the source.'),
('Obstructive','Not developed as a separate adult category in this chapter. The pediatric chapter supplies mechanical obstruction as the initiating failure.','Adult-specific manifestations and complete management are missing.')], '48:8,9,10,11,12,14,15,16,17,18,19,20,21,22,24')
card(49,'Pediatric shock: distinguish perfusion from pressure',['Type or state','Findings and mechanism','Source-supported response'],[
('Compensated versus hypotensive','Poor perfusion may coexist with age-appropriate systolic pressure. Hypotension defines a later category. Hypoxia is a common cause of bradycardia in severe illness.','Assess perfusion, oxygen delivery and the cause. Blood pressure alone is insufficient.'),
('Hypovolemic','Inadequate volume relative to vascular space. Compensation retains sodium/water and redistributes circulation. Young infants have limited glucose and renal reserve.','Oxygen, volume replacement and blood components when needed; monitor glucose, electrolytes, temperature, urine and pressures. The slide excludes hypotonic replacement fluids.'),
('Cardiogenic','Myocardial impairment after surgery, inflammatory heart disease, drug toxicity or electrolyte imbalance. Cool extremities, mottling and delayed refill occur.','Titrate fluid to preload and use vasoactive support for myocardial function/systemic perfusion.'),
('Septic','Infection-associated mediators cause vasodilation, leakage, maldistribution and cardiovascular dysfunction. Cold shock has vasoconstriction, weak pulses and prolonged refill; warm shock has vasodilation and bounding pulses.','The deck emphasizes early fluids, antibiotics and titrated vasoactive support. Numerical targets and complete regimens require matching course protocols; disputed lactate units are excluded.'),
('Neurogenic','Severe head/spinal injury causes loss of vasomotor tone, hypotension and absent compensatory tachycardia.','Positioning, bolus fluids, vasopressors and temperature management are listed; no dosing algorithm is supplied.'),
('Obstructive','Mechanical impediment to filling or flow; examples include tamponade, pulmonary embolism and obstructive congenital lesions.','Restore oxygenation/perfusion and relieve the cause. The deck lists selected decompression, catheter, prostaglandin and fibrinolytic approaches, not interchangeable treatment for every cause.'),
('Anaphylactic','Named under distributive shock. Pediatric-specific manifestations and management are not developed.','Adult mechanism is available; complete pediatric management remains a gap.')], '49:5,6,9,10,11,17,18,25,26,27,28,29,33,34,35,37,38,39')
card(48,'Burn depth and consequences',['Tissue depth','Supplied findings','Supported care and limits'],[
('Epidermal only','Pain and erythema, without underlying dermal destruction. The deck inconsistently calls this partial-thickness/first-degree.','Use the tissue description to avoid the label conflict. Detailed outpatient care is absent.'),
('Superficial dermal injury','Pain and thin-walled fluid-filled blisters developing quickly.','Wound care is taught generally; depth-specific full protocols are absent.'),
('Deep dermal injury','Waxy white appearance; appendages can remain. Distinction from full thickness may become clearer as skin buds and hair appear.','Excision/grafting is discussed for deeper injury; complete decision criteria are absent.'),
('Full-thickness destruction','Entire epidermis and dermis, often subcutaneous tissue. Dry/leathery white, red or black wound; rare blisters; sensory endings destroyed.','Specialized wound management, excision and grafting. Escharotomy releases underlying pressure when indicated by the course context.'),
('Systemic injury','Circulating depletion can coexist with edema. Evaporative loss, immunosuppression and hypermetabolism accompany severe burns.','Replace fluid and monitor urine output. Early enteral support and infection prevention are listed. Capillary seal is the source\'s endpoint of burn shock.'),
('Severity and extent','Age, medical history, site, depth and extent matter. Rule of nines and age-adjusted Lund–Browder charts are named.','No validated chart or worked calculation is supplied; the pediatric lower-limb percentage is quarantined.')], '48:42,43,44,45,46,47,48,49,50,51,52,54,55')
card(49,'Pediatric burn complications and recovery',['System','Mechanism and manifestations','Care or discriminator'],[
('Skin and circulation','Direct/evaporative losses and edema can involve unburned tissue; cardiac output falls initially.','Children\'s greater surface area relative to weight increases fluid need. The modified Parkland formula is named but not supplied.'),
('Airway and lungs','Inhalation injury, edema, aspiration and pneumonia may occur. Small edema increases breathing work; soft airway cartilage and pliable chest add vulnerability.','Attend to oxygenation, ventilation and fatigue. No complete airway protocol is provided.'),
('Renal and gastrointestinal','Edema mobilizes during recovery; mucosal atrophy and permeability changes can enable bacterial translocation, and ileus may occur.','Urine output tracks replacement. Intraosseous access is listed if venous access fails. Electrical-injury-specific renal pathophysiology remains missing.'),
('Infection and metabolism','Immature immunity and prolonged immunosuppression increase infection risk. Limited glycogen accelerates protein/lipid catabolism and lean-mass loss.','Meticulous wound care and nutrition support. The initial ebb phase gives way to hypermetabolic flow after circulation is restored.'),
('Wound closure','Deep dermal/full-thickness wounds may require excision and grafting once hemodynamically stable.','The source distinguishes sheet and mesh graft selection by extent.'),
('Growth and recovery','Scars can restrict joints as the child grows. Background and procedural pain are difficult to measure in infants.','Prolonged scar/contracture management, PT, OT, psychosocial care and school reintegration may be needed. Wound closure does not end rehabilitation.')], '49:46,48,49,50,51,52,53,54,56,57,58,59,60,61,62,63,64,65,66')
(P/'supplemental-cards.json').write_text(json.dumps(D,indent=2))
