"""Assemble personally authored Unit 4 content. No question generation or network calls.
Run from worktree root. Private packet stays external; only selected disclosures enter site.
"""
from pathlib import Path
import json,re,html,hashlib,shutil
ROOT=Path(__file__).resolve().parents[4]
PACKET=Path('/Users/ethanheinrick/Desktop/NU545 Unit 4')
OUT=ROOT/'site/nu545/exam4'; DOC=ROOT/'docs/nu545/exam4'
E=html.escape
slides={}; manifests={}; notes={}
index=json.loads((PACKET/'collection-index.json').read_text())
for entry in index['entries']:
 folder=PACKET/entry['folder']; m=json.loads((folder/'manifest.json').read_text());ch=m['chapter']
 if ch in manifests:continue
 manifests[ch]=m; data=json.loads((folder/'slide-and-notes-text.json').read_text())
 for s in data['slides']:slides[f'CH{ch}S{s["slide"]}']=s['text']
 # Existing note text is reused. The original relationship must be verified for citations.
 import zipfile,xml.etree.ElementTree as ET,posixpath
 with zipfile.ZipFile(next(folder.glob('*.pptx'))) as z:
  for s in data['slides']:
   rel=f'ppt/slides/_rels/slide{s["slide"]}.xml.rels'
   if rel not in z.namelist():continue
   for r in ET.fromstring(z.read(rel)):
    if r.attrib['Type'].endswith('/notesSlide'):
     part=posixpath.normpath(posixpath.join('ppt/slides',r.attrib['Target']))
     n=next((n for n in data['notesParts'] if n['xmlPart']==part),None)
     if n and len(n['text'])>30:notes[f'CH{ch}S{s["slide"]}N']=n['text']

def refs(ch,nums):return [f'CH{ch}S{n}' for n in nums]
L={'CONFIG':{'id':'nu545-exam4','courseCode':'NU545','courseTitle':'Physio-Pathological Basis for Advanced Nursing','examLabel':'Exam 4','title':'NU545 · Exam 4','subtitle':'Blood, circulation and cardiovascular alterations','storageKey':'nu545-exam4-progress-v1','examDate':'2026-10-19','callout':'Supported slide content; exact textbook gaps remain visible.','mockRationale':'Practice design: three distinct 25-question forms, 40 minutes each. Official count, timing, attempts, weights and item mix are unconfirmed. Forty exam points do not establish forty questions.'},'SECTIONS':[],'CONCEPTS':{},'GUIDE':{},'ITEMS':[],'CASES':[],'BOSSES':[],'DOMAINS':{'blood':{'name':'Hematology'},'cardiac':{'name':'Cardiovascular'}},'FORMS':{f:[] for f in 'ABC'},'MOCK_BLUEPRINTS':{'25':{'domains':{'blood':16,'cardiac':9},'includeCase':False}},'SOURCES':{},'SOURCE_HTML':{},'COVERAGE':{'updatedAt':'2026-10-01','prompts':[]},'VISUALS':[],'DNA':["Unit 4 DNA revision u4-personal-2026-10-01-r1. Six released four-choice MCs and twenty prose questions; linked cases and neighboring mechanism contrasts. Instructor authorship and recurrence unverified.","Original options match category, grammar and detail; explanations follow checking. All new questions are personally authored and separately reviewed against the packet. Practice form allocations are not predicted weights."],'GEN_FOR':{},'ACADEMIC_FIGURES':[]}
for ch in range(28,34):
 title=manifests[ch]['title'].split(': ',1)[1]
 if ch==29:title='Alterations of Hematologic Function'
 L['SECTIONS'].append({'id':f'ch{ch}','n':ch,'title':title,'short':title,'dom':'blood' if ch<31 else 'cardiac','src':f'CH{ch}S'+str({28:12,29:13,30:6,31:11,32:12,33:6}[ch])});L['GUIDE'][f'ch{ch}']=[]

def card(ch,key,title,prompts,nums,body,limit='',mastery=True):
 c=f'u4-c{ch}-{key}';ss=refs(ch,nums)
 L['CONCEPTS'][c]={'sec':f'ch{ch}','name':title,'guidePrompts':prompts,'mastery':mastery}
 L['GUIDE'][f'ch{ch}'].append({'id':f'u4-g{ch}-{key}','h':title,'html':''.join('<p>'+E(p)+'</p>' for p in body.split('\n\n')),'c':[c] if mastery else [],'src':ss,'tier':1,'conflict':limit})

card(28,'cells','Blood cells: shape, role and life span',[25,27],[12,13,14,15,16,17,18,19,20,21,23],'''Erythrocytes carry hemoglobin for tissue oxygenation. Their biconcave shape favors gas diffusion; reversible deformability lets them pass through small vessels. The adult life span is 120 days. Platelets are nondividing megakaryocyte fragments that control bleeding and support coagulation; their listed life span is 8–11 days before splenic removal.

Neutrophils phagocytose microbes and debris in early inflammation; immature forms are bands. Eosinophils ingest antigen–antibody complexes and viruses, release inflammatory mediators, and increase with type I allergy and parasites. Basophils release histamine and chemotactic mediators. Mast-cell degranulation increases vascular permeability and smooth-muscle contraction. Lymphocytes mediate immune responses. NK cells kill tumor and virally infected cells without prior antigen induction. Monocytes become macrophages or dendritic cells; macrophages clear damaged cells, present antigen and support repair.''')
card(28,'production','Production changes with age and oxygen demand',[9,28,29],[30,31,32,33,34,35,36,38,39,63,64,65,66],'''Hematopoietic stem cells generate the blood-cell lineages; marrow niches regulate differentiation. Adult active marrow includes pelvic bones, vertebrae, skull/mandible, sternum/ribs, humerus and femur. Proliferation and differentiation replace lost or aging cells. Fetal production occurs in liver/spleen; the age sequence is expanded in Chapter 30.

Renal hypoxia stimulates erythropoietin, increasing marrow RBC production and release. Reticulocytes index current production. During erythrocyte maturation, hemoglobin increases while nuclear size decreases. Newborn counts and reticulocytes start high; full-term RBC life span is 60–80 days, premature RBC life span 20–30 days. Neonatal platelet counts are comparable to adult counts. Age-specific numeric reference intervals are not supplied.''','Obtain complete infant normal/abnormal reference ranges; do not substitute adult cutoffs.')
card(28,'iron','Hemoglobin, nutrients and the iron cycle',[26,29,34],[40,41,42,44,45],'''Adult HbA has two alpha and two beta chains. Heme contains iron-protoporphyrin and is synthesized in mitochondria; each heme can carry one oxygen molecule. Amino acids support structure and hemoglobin synthesis. B12 and folate support RBC maturation; folate supports DNA/RNA synthesis. The slides associate B6, E and pantothenic acid with heme synthesis and list C, riboflavin and niacin among nutritional requirements.

Macrophages, usually splenic, remove senescent RBCs. Heme porphyrin becomes bilirubin; globin yields amino acids; iron is recycled. Transferrin transports circulating iron, ferritin stores intracellular iron, and hemosiderin is described as ferritin micelles. Hepcidin governs iron homeostasis. Apotransferrin and apoferritin are the iron-free precursors.''','Methemoglobin and the complete enzymatic synthesis/absorption pathway are missing. CH28S40 molecule-count wording is quarantined.')
card(28,'hemostasis','From vascular injury to clot removal',[30],[49,50,51,52,53,54,55,56,57,59,60],'''Injury causes vasoconstriction, platelet-plug formation and coagulation, followed by retraction and fibrinolysis. Platelet GPIb binds von Willebrand factor for adhesion. Activation changes platelet shape and releases granules; fibrinogen bridges support aggregation. Retraction compacts the fibrin mesh. Intrinsic activation involves factor XII contacting exposed subendothelial material; extrinsic activation involves tissue factor. Both converge on factor X, thrombin and fibrin.

Intact endothelium restrains clotting through nitric oxide/prostacyclin and anticoagulant mechanisms. Antithrombin inhibits thrombin and activated factors; TFPI inhibits initiation; thrombomodulin binds thrombin; protein C with protein S degrades Va/VIIIa. tPA/uPA activate plasminogen to plasmin, which degrades fibrin. Chapter 29 names vitamin K deficiency as a coagulation defect.''','Exact vitamin K dependent factor inventory and full synthesis pathway are not supplied. Platelet cutoffs differ across slides; no universal threshold is scored.')
card(28,'lymph','Filtering blood, filtering lymph',[31,32,40],[9,24,25,26,27,28,29],'''The spleen filters blood, removes aged erythrocytes, stores blood and responds to bloodborne organisms. Removal increases the risk of encapsulated bacterial infection through loss of the stated IgM response. Lymph nodes filter lymph and bring antigens together with lymphocytes and antigen-processing macrophages. Chapter 29 connects localized tender enlargement to drainage from nearby inflammation.

Albumin carries substances and controls plasma oncotic pressure. The packet supports this function but does not fully explain the consequences of low albumin. Do not confuse the spleen’s blood filter with the nodes’ lymph filter.''','Full low-albumin consequences and management require the textbook; the complete cellular sequence of inflammatory node enlargement is not taught.')
card(29,'anemia','Classify anemia before choosing its mechanism',[33,34],[13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29],'''Anemia reflects too few erythrocytes or insufficient/abnormal hemoglobin. Production failure, blood loss and increased destruction can combine. Reduced oxygen carriage explains dyspnea, palpitations, dizziness, fatigue and pallor. Size uses “-cytic”; hemoglobin content uses “-chromic.” Anisocytosis means varied size; poikilocytosis means varied shape.

B12 or folate deficiency impairs DNA synthesis while RNA processes continue, producing large precursors with mismatched nuclear/cytoplasmic maturation. Pernicious anemia involves deficient intrinsic factor and impaired B12 absorption, with possible paresthesias, gait difficulty and glossitis. Folate deficiency can produce cheilosis, stomatitis and GI symptoms; neurologic symptoms are usually absent. Iron deficiency is microcytic/hypochromic, can cause spoon-shaped nails, and is evaluated with ferritin. Treatment addresses blood loss and replaces iron. Acute hemorrhage requires volume/blood replacement according to severity.''','Full anemia differential, compensation mechanisms, treatment selection and subtype-specific diagnostics are incomplete; objectives alone are not factual support.')
card(29,'b12','B12 replacement and the absorption distinction',[35],[20,21,22,23,24],'''Intrinsic factor from gastric parietal cells is needed for effective B12 absorption. The released pernicious-anemia case uses IM replacement because absorption is impaired. Slide 22 also explicitly permits high oral doses or weekly/monthly injections; the case does not establish that every oral regimen fails.

Folate is absorbed in the upper small intestine without an analogous facilitating factor. Its deficiency can be treated orally until blood levels normalize. Both deficiencies affect nuclear maturation, but the packet distinguishes the neurologic manifestations of B12 deficiency.''','No time course or criteria for confirming B12 treatment response are supplied. The slide’s absolute neurologic irreversibility statement is not used as a scored rule.')
card(29,'marrow','Production failure, destruction and inflammatory iron restriction',[33],[30,31,32,34,35,36,38,39,40,41,42],'''Anemia of inflammation combines shortened RBC survival, suppressed erythropoietin, impaired marrow response and altered iron handling. Iron may be stored abundantly but unavailable; conventional iron replacement may fail, so the underlying disease matters.

Aplastic anemia can reduce all three cell lines, with hypocellular marrow replaced by fat. Pure red-cell aplasia affects only RBCs. Evaluation uses blood testing and marrow biopsy; listed treatment includes transplantation or immunosuppression. Hemolytic anemia accelerates destruction within vessels or through extravascular removal. It may cause jaundice and splenomegaly with erythroid hyperplasia. Autoimmune forms target RBC antigens; PNH involves CD55/CD59 deficiency and complement-mediated lysis. Management depends on the cause.''','Detailed sideroblastic, hemolytic subtype and chronic-disease algorithms are not fully supplied.')
card(29,'polycythemia','Relative and absolute red-cell excess',[36],[43,44,45,46,47,48],'''Relative polycythemia concentrates existing cells as plasma volume falls; hydration resolves that relative change. Absolute polycythemia increases the RBC mass. Secondary absolute polycythemia reflects increased erythropoietin from hypoxia or an erythropoietin-secreting tumor.

Polycythemia vera involves constitutive JAK2-linked receptor activity, independent of normal erythropoietin regulation. Increased cellularity raises viscosity, with splenomegaly, elevated pressure, thrombosis and aquagenic pruritus among listed manifestations. Phlebotomy reduces cell excess and volume; the deck also lists aspirin, interferon and hydroxyurea.''','A complete diagnostic pathway and detailed treatment selection are missing.')
card(29,'mono','Mononucleosis and reactive leukocyte changes',[1,37],[54,56,60,61,62,64,65,66,67],'''Infectious mononucleosis is an acute viral illness involving B lymphocytes, commonly EBV. Salivary contact is the usual transmission route. Fever, pharyngitis and cervical lymphadenopathy form the listed classic triad. The packet names heterophile-antibody testing with Monospot. Rest and symptom relief are supported; the slide warns against aspirin in children/adolescents.

A left shift means premature release of immature leukocytes as demand exceeds supply. Eosinophils increase in hypersensitivity and parasitic disease, with mast-cell chemotactic signals contributing. Basophils also increase in hypersensitivity and release histamine.''','Mono complications and confirmatory-test limitations are missing. The slide’s unexplained antibiotic list is quarantined rather than taught as routine viral therapy.')
card(29,'leukemia','Cell lineage, maturity and marrow consequences',[2],[69,70,71,72,73,74,75,76,77,79,80,81,82,83,84],'''Leukemias are classified by lineage (myeloid/lymphoid) and progression (acute/chronic). Acute forms feature immature blasts; chronic forms predominantly contain mature but dysfunctional cells. Malignant expansion displaces normal hematopoiesis, linking anemia to fatigue, thrombocytopenia to bleeding and deficient functional leukocytes to infection.

ALL is emphasized in childhood; AML arises from myeloid precursors. CML is associated with the Philadelphia chromosome/BCR-ABL1; CLL involves monoclonal B cells, lymphadenopathy and impaired humoral immunity. Evaluation uses blood smear and marrow studies. The slides list chemotherapy, transplant and supportive treatment for infection/cytopenias. Chronic CML may proceed to an accelerated or blast phase.''','Do not score outdated/categorical cure or survival claims, the isolated 30% diagnostic threshold, or CH29S79 apoptosis wording. Subtype-specific diagnostic and treatment criteria need textbook support.')
card(29,'lymphoma','Lymphoid tumors and tissue diagnosis',[4,5,6],[85,86,87,88,89,90,91,92,93,94,95,96,97,98],'''Lymphomas arise from malignant lymphocytes in lymphoid tissues. Hodgkin lymphoma includes Reed-Sternberg cells derived from malignant B cells, often binucleate; the slide says they are necessary but not specific. Painless neck nodes, pressure effects, fever, weight loss, night sweats and pruritus are listed. Biopsy is the strongest supplied diagnostic evidence. Treatment options include chemotherapy, radiation, antibodies and transplantation.

Non-Hodgkin disease includes B, T and NK lineages, often with painless nodal or abdominal masses; biopsy establishes tissue diagnosis. Treatment varies by type/stage. Burkitt lymphoma is an aggressive B-cell tumor: jaw/facial involvement is described in Africa, abdominal swelling in US cases. Evaluation uses tissue or marrow; chemotherapy and adjunct rituximab are listed. Lymphoblastic lymphoma usually arises from immature T cells in the thymus.''','Complete staging, complications and subtype-specific treatment algorithms are missing; the undifferentiated EBV percentage is not scored.')
card(29,'myeloma','Plasma-cell products link bone and kidney injury',[3],[100,101,102,103],'''Myeloma involves marrow plasma-cell proliferation and excess production of one immunoglobulin class. M protein is the abnormal antibody; free light chains (Bence Jones proteins) may pass the glomerulus and injure renal tubular cells.

The listed pattern joins lytic bone lesions and pain with hypercalcemia, anemia, renal failure, hyperviscosity and recurrent infections. Evaluation includes radiographic/laboratory studies and marrow biopsy. Listed management targets the malignancy and complications: chemotherapy/targeted or biologic therapy, transplantation, bisphosphonates, hydration and infection treatment.''','Detailed diagnostic criteria and electrolyte management thresholds are not supplied.')
card(29,'platelets','Platelet loss is different from defective platelet function',[15,16],[105,106,107,108,109,110,111,112,113,114,115,116],'''HIT is an immune adverse reaction involving IgG against heparin–platelet factor 4. Platelet reduction can coexist with thrombosis; the packet explicitly says to stop heparin. Detailed probability scores, testing and substitute anticoagulants are absent.

ITP antibody-coated platelets are removed from circulation, producing petechiae/purpura. TTP instead involves microvascular platelet aggregation with thrombocytopenia, hemolytic anemia, neurologic ischemia, renal failure and fever. Essential thrombocythemia produces excessive platelets through abnormal megakaryocyte progenitors. A normal platelet count does not exclude qualitative dysfunction: adhesion, aggregation, secretion or membrane pathways can fail.''','Specific HIT diagnostic/management algorithm is missing; cross-deck platelet threshold differences are not graded.')
card(29,'dic','Why thrombosis and bleeding can coexist',[7,8],[117,118,119,120,122,123,124,125,126],'''DIC is acquired, widespread, ongoing clotting with simultaneous bleeding. Tissue-factor exposure increases thrombin/fibrin activity; microvascular fibrin impairs perfusion. Consumption of platelets and coagulation factors then makes bleeding more likely. Venipuncture/wound bleeding, purpura, petechiae, hematomas and distal cyanosis are listed. Treatment addresses the cause, thrombosis, organ support and replacement needs.

Virchow’s triad connects endothelial injury, abnormal flow and hypercoagulability. Thrombi stay fixed; emboli move before lodging. Hereditary thrombophilias involve hemostatic-protein defects; the deck says most are autosomal dominant. Chapter 30 adds protein C/S and antithrombin deficiencies.''','A complete DIC diagnostic lab pattern and treatment indications are missing. Specific named mutations and genotype-risk details require textbook clarification.')
card(30,'neonatal','From fetal production to newborn hemolysis',[9,10,11,28],[6,7,8,9,14,15,16],'''Production begins in the yolk-sac vessels, shifts to liver sinusoids at eight weeks, begins in marrow by five months and is chiefly marrow at delivery in the supplied sequence. HbF contains alpha/gamma chains and has greater oxygen affinity than adult hemoglobin. Adult percentages become established at 6–12 months. RBC numbers fall during the first two to three months; lymphocytes can rise in the first year before declining.

HDFN is alloimmune: maternal antibodies, usually IgG, cross the placenta and bind incompatible fetal RBC antigens, producing hemolysis or splenic clearance. Anemia, hepatosplenomegaly, bilirubin excess and neonatal jaundice may result. Kernicterus means bilirubin deposition in the brain. The packet names Coombs testing, Rh immune globulin prevention, phototherapy and exchange transfusion.''','Age-specific numeric blood intervals, diagnostic interpretation and treatment thresholds are missing; prevention and treatment must remain distinct.')
card(30,'g6pd','Oxidative injury versus membrane instability',[12],[18,19,20,21],'''G6PD deficiency is X-linked recessive. Without adequate enzyme protection, oxidative stress damages hemoglobin and RBC membranes, shortening survival and producing Heinz bodies. Pallor, jaundice, dark urine and back pain can accompany acute hemolysis; between attacks the slide describes normal RBC survival without anemia.

Hereditary spherocytosis is a membrane-protein disorder, often involving spectrin/ankyrin. Less deformable cells are vulnerable to splenic sequestration. The source describes autosomal dominant inheritance, anemia/jaundice/splenomegaly, blood smear and osmotic fragility testing, folate and possible partial splenectomy.''','Specific G6PD assay/trigger lists and evidence-based treatment selection are not supplied. Oral iron is not scored as universal hemolysis treatment.')
card(30,'sickle','Sickling changes both flow and cell survival',[13],[22,23,24,26,27,28,29],'''Sickle cell disease involves HbS and autosomal recessive inheritance. Deoxygenation, dehydration, acidosis and cold favor sickling. Polymerization stiffens RBCs, reducing deformability and obstructing microcirculation. This is a change in the cell and its blood-flow behavior, not simply a change in hemoglobin quantity.

Vasoocclusive crises cause pain; acute chest syndrome involves sickled cells in an injured/underventilated lung. Aplastic crisis interrupts production; sequestration pools blood in the spleen; hyperhemolytic crisis accelerates destruction. Renal concentrating defects, infection and gallstones are listed complications. The deck emphasizes avoiding triggers, treating pain/infections, correcting dehydration/acidosis and oxygen when hypoxic; hydroxyurea is listed.''','CH30S22 amino-acid substitution direction is quarantined. Diagnostic assays and complete therapeutic detail require the textbook.')
card(30,'thalassemia','Globin-chain production and disease burden',[14],[30,31,32,33,34],'''Thalassemias are autosomal recessive disorders of slowed or defective alpha- or beta-globin synthesis. The source distinguishes major/homozygous from minor/heterozygous forms. Beta minor typically produces mild microcytic/hypochromic anemia; beta major has absent HbA and a severe cardiovascular burden.

The alpha series is described by affected genes: one (trait), two (minor), three (HbH disease), four (major). Major alpha disease is associated with hydrops and severe fetal heart failure. Listed major-disease management includes transfusion, iron chelation, genetic counseling, splenectomy and transplantation.''','Complete diagnostic tests, variant-level interpretation and complication management are missing.')
card(30,'bleeding','Factor deficiency versus immune platelet destruction',[15],[35,36,37,39,40,41],'''Hemophilia A reduces factor VIII; B reduces factor IX. A is X-linked in the slides, with recessive inheritance specified in S38 notes. Persistent bleeding and hematoma formation accompany prolonged PTT with normal PT. The replacement factor matches the deficiency. Von Willebrand disease involves deficient/dysfunctional vWF and reduced factor VIII activity; autosomal dominant inheritance is stated.

Primary immune thrombocytopenia binds platelet membranes with antibodies and increases removal. Bruising, petechiae and asymmetric bleeding are listed; IVIG and corticosteroids are named. The supplied pediatric course describes frequent recovery within three months. Neonatal alloimmune thrombocytopenia instead follows maternal immunization against paternally derived fetal platelet antigens.''','Detailed B/C inheritance, factor inhibitors, disease-specific complications and complete work-up are not provided.')
card(31,'flow','Follow the chambers, valves and pressure phases',[17,19],[11,15,16,17,18,19,20,21,22,23,25,26,27,28,43,44,45,46,47],'''Systemic venous blood enters the right atrium, crosses the tricuspid valve to the right ventricle and exits through the pulmonic valve to the lungs. Pulmonary veins return oxygenated blood to the left atrium, then the mitral valve/left ventricle, then the aortic valve/systemic circulation. The right circuit is lower pressure; the left circuit is higher pressure.

Diastole fills the ventricles; systole ejects blood. The supplied phases distinguish atrial systole, isovolumetric contraction, ejection, isovolumetric relaxation and passive filling. Preload is end-diastolic filling; afterload is resistance to ejection. Cardiac output is heart rate times stroke volume; ejection fraction is stroke volume divided by end-diastolic volume. Coronary arteries nourish myocardium, with collateral connections offering alternative routes; the coronary sinus drains into the right atrium.''','Precise pressure ranges and artery-by-artery occlusion territories are missing; the ostial wording in S28 is not used as a scored location rule.')
card(31,'electric','Electrical activation and pumping are related but different',[18],[29,30,31,33,34,35,40,41,42],'''The conduction sequence runs from SA node through atrial pathways and AV node, His bundle, bundle branches and Purkinje fibers to ventricular myocardium. Automaticity generates spontaneous depolarization; rhythmicity is regular generation. Refractoriness permits relaxation rather than continuous contraction.

The P wave is atrial depolarization. PR spans onset of atrial to onset of ventricular activation. QRS sums ventricular depolarization; ST represents depolarized ventricular myocardium; QT spans ventricular electrical systole. Calcium binds troponin to permit cross-bridge cycling; relaxation begins as calcium is released from troponin. Electrical events are not interchangeable with mechanical ejection.''','A complete waveform/interval reference including T wave and all abnormal patterns is not supplied.')
card(31,'beta','Receptors, force and blood-pressure regulators',[20,21],[35,36,37,50,51,52,61,62,64,65,67,68,69,70,73,74],'''Beta 1 and beta 2 stimulation increase heart rate and force in the supplied cardiac context. Beta 2 also increases coronary flow. Beta 3 decreases myocardial contractility and may restrain overstimulation. Chronotropy changes rate; inotropy changes force. Parasympathetic activity slows conduction and reduces force.

Angiotensin II constricts vessels; aldosterone increases sodium/chloride/water retention. Natriuretic peptides promote loss of those substances and reduce volume. ADH conserves water. A falling pressure triggers baroreflex tachycardia and arteriolar constriction. Veins are compliant reservoirs aided by muscle/respiratory pumps; lymphatic vessels return excess fluid to veins.''')
card(32,'pressure','Hypertension links output, resistance and organ injury',[21],[19,20,21,22,23,24,25,26,27,28],'''Pressure rises when cardiac output, peripheral resistance or both rise. Primary hypertension involves genetic/environmental effects mediated through sympathetic activity, RAAS, volume and vascular tone. Secondary hypertension follows another disease or drugs. Risk factors include family history, age, sodium intake, diabetes, obesity, smoking and heavy alcohol use.

Early hypertension may have no symptoms. The packet describes repeated seated measurements after rest rather than a single rushed reading. Persistent pressure contributes to MI, kidney disease, stroke and vascular remodeling. Listed approaches include risk reduction, DASH, smoking cessation, exercise and several antihypertensive classes, including ACE inhibitors/ARBs/aldosterone antagonists, calcium-channel blockers and thiazide combinations.''','The deck uses a 140/90 threshold; it is dated course wording, not a universal current clinical rule. Full RAAS sequence and treatment selection require the designated textbook.')
card(32,'vascular','Venous pooling and digital vasospasm',[38,39],[12,13,14,41,42,43,44,45,47],'''Varicose veins develop when incompetent valves, obstruction or muscle-pump dysfunction permit pooling, distortion and elevated hydrostatic pressure. Persistent ambulatory venous hypertension produces chronic venous insufficiency. Leg elevation, compression and movement are listed approaches. DVT adds thrombus/embolus risk through stasis, injury and hypercoagulability.

Raynaud disease is primary episodic digital vasospasm of unknown origin; Raynaud phenomenon is secondary to another condition. Ischemia changes skin color and sensation. This contrasts with atherosclerotic plaque, where lipid-laden macrophages and inflammation produce a fatty streak and fibrous lesion. Arterial narrowing impairs tissue perfusion.''')
card(32,'infection','Immune injury and infected vegetations',[22,23],[78,83,84,85,86,87],'''Rheumatic fever follows a delayed immune response to group A beta-hemolytic streptococcal infection. Cross-reactivity involving M proteins can injure tissue; Aschoff bodies are described. Carditis, large-joint polyarthritis, nodules, chorea and erythema marginatum are listed findings. Mitral stenosis is linked to prior rheumatic fever. Antibiotics and anti-inflammatory treatment are included in the packet.

Infective endocarditis proceeds through endocardial damage, adherence of bloodborne organisms and infected vegetation formation. Fever, changed murmur, petechiae, emboli and heart failure may follow. Osler nodes are painful finger/toe-pad nodules; Janeway lesions are nonpainful palm/sole lesions. Antibiotics over weeks and indicated valve surgery are listed.''','Formal rheumatic-fever diagnostic criteria, prophylaxis duration decisions, endocarditis cultures/echo criteria and organism-specific regimens are missing.')
card(32,'failure','Connect impaired pump function to congestion',[17,21],[88,89,90,91,92,93,94,95,96],'''Heart failure means inadequate output for tissue needs and/or elevated filling pressure. Systolic dysfunction reduces pumping performance; diastolic dysfunction reduces ventricular compliance and relaxation despite preserved EF. Hypertension raises afterload, increasing workload. Neurohumoral responses include sympathetic and RAAS activity.

Left failure produces pulmonary congestion with dyspnea/orthopnea and frothy sputum. Right failure produces systemic venous congestion, peripheral edema, JVD and hepatosplenomegaly. Either may coexist with the other. Treatment targets listed in the deck include reducing preload/afterload and improving contraction. High-output failure can occur even with normal/elevated contractility when demand is excessive. The released Chapter 32 case is supplementary teaching beyond a separately named HF guide prompt.''')
card(33,'shunts','Shunts change where oxygenated blood travels',[24],[6,7,8,9,10,11,22,23,24,25,26,27,28],'''High-pressure left-to-right shunts increase pulmonary flow. VSD joins ventricles; ASD joins atria. In the supported VSD pattern, oxygenated blood is sent back toward the lungs, so initial cyanosis is not required. Defect size and pulmonary resistance influence the burden. The released VSD case identifies a harsh systolic murmur at the left lower sternal border; PDA is described with a continuous machinery murmur.

TOF combines VSD, overriding aorta, pulmonary stenosis and right-ventricular hypertrophy. Reduced pulmonary flow contributes to cyanosis; squatting is a described compensation. Tricuspid atresia blocks communication from right atrium to right ventricle and accompanies septal defects, right-ventricular underdevelopment, enlarged left structures and pulmonic stenosis. Transposition creates parallel circuits, requiring communication for survival; TAPVC returns pulmonary veins to the right side, and truncus leaves a shared arterial outlet.''','Complete murmur locations and compensation mechanisms are missing. PDA direction and the shifted case answer labels are flagged. Do not score obligatory squatting-induced reversal.')
card(33,'obstruction','Outflow obstruction and infant compensation',[24],[13,14,15,16,18,19,20,21,30,31,32],'''Coarctation narrows the aorta. Older children may have upper-extremity hypertension with weak lower-extremity pulses; a newborn may deteriorate as the ductus closes. Aortic stenosis increases left-ventricular workload; severe forms may cause syncope/exertional pain. Pulmonary stenosis obstructs right-ventricular outflow. Hypoplastic left heart reduces systemic output as the ductus closes.

Children with heart failure may feed poorly, fail to thrive, breathe rapidly, sweat and develop hepatomegaly. Increased wall stress leads to hypertrophy; listed care reduces workload, improves efficiency and supports calories. Surgical approaches depend on anatomy; the packet lists staged repair for hypoplastic left heart. Murmur presence alone does not supply every requested auscultatory location.''','Obtain a complete defect-by-defect murmur/location and compensation table. The packet does not justify inventing missing findings.')
# Component-level adjudication: support is at supplied slide depth, never textbook completeness.
# Each component is status | component | exact source IDs | supported content or specific gap.
coverage_specs={
1:[('Direct','Pathophysiology/etiology','CH29S65','Acute B-lymphocyte viral infection; EBV; salivary route'),('Direct','Manifestations','CH29S66','Classic fever/pharyngitis/cervical nodes'),('Partial','Diagnostics','CH29S66','Monospot named; sensitivity, interpretation and confirmation missing'),('Partial','Treatment','CH29S67','Rest and symptom relief; antibiotic indication not explained and gated'),('Missing','Complications','','No mononucleosis complication teaching supplied')],
2:[('Direct','Lineage and acute/chronic pathophysiology','CH29S69 CH29S70 CH29S72 CH29S74 CH29S79','ALL/AML/CML/CLL cell and progression contrasts; apoptosis wording excluded'),('Direct','Manifestations/complications','CH29S75 CH29S77 CH29S80 CH29S81','Cytopenias, infection, bleeding, nodes and blast phase'),('Partial','Diagnostics','CH29S76 CH29S82','Blood/marrow named; subtype criteria missing and isolated blast cutoff gated'),('Partial','Treatment','CH29S76 CH29S77 CH29S82','Treatment categories; subtype protocols and response criteria absent')],
3:[('Direct','Pathophysiology','CH29S101','Plasma cells, M protein, light-chain renal injury'),('Direct','Manifestations/complications/electrolytes','CH29S102','Lytic bone disease, renal failure, hypercalcemia, anemia, infection'),('Partial','Diagnostics','CH29S102','Radiographic/lab/marrow studies named, criteria absent'),('Direct','Treatment categories','CH29S103','Malignancy, skeletal, renal and infection targets at slide depth')],
4:[('Direct','Pathophysiology','CH29S87 CH29S88 CH29S89 CH29S90 CH29S93 CH29S94','Hodgkin versus non-Hodgkin lineage and malignant expansion'),('Direct','Manifestations','CH29S91 CH29S95','Painless nodes, systemic symptoms, pressure/mass effects'),('Partial','Diagnostics','CH29S91 CH29S95','Biopsy and imaging named, staging absent'),('Partial','Treatment/complications','CH29S92 CH29S96','Categories and pressure effects; complete subtype complications and selection absent')],
5:[('Direct','Definition and diagnostic qualifier','CH29S89','Often binucleate transformed B cells; necessary but not specific in supplied wording')],
6:[('Direct','Pathophysiology/manifestations','CH29S97','Aggressive B-cell NHL; jaw versus abdominal presentations'),('Partial','Diagnostics','CH29S97','Biopsy/marrow named; criteria absent'),('Direct','Treatment categories','CH29S97','Chemotherapy and adjunct rituximab'),('Missing','Complications','','No specific complication account')],
7:[('Direct','Pathophysiology','CH29S117 CH29S118','Tissue-factor activation, microthrombi, consumption and bleeding'),('Direct','Manifestations/complications','CH29S118 CH29S119','Bleeding and organ hypoperfusion'),('Missing','Diagnostics','','No complete diagnostic lab pattern'),('Partial','Treatment','CH29S120','Goals supplied; specific replacement/anticoagulant indications absent')],
8:[('Partial','Genetic thrombophilia','CH29S124 CH29S125 CH30S39 CH30S45N','Protein C/S and AT defects, APC resistance in notes; exact mutations and genotype risks missing')],
9:[('Partial','Normal/abnormal infant values','CH28S63 CH28S64 CH28S65 CH28S66 CH30S8 CH30S9','Developmental trends and RBC life spans; complete numeric CBC/reference intervals missing')],
10:[('Direct','Pathophysiology','CH30S14 CH30S15','Maternal IgG, antigen incompatibility and fetal RBC destruction'),('Direct','Manifestations/complications','CH30S16','Anemia, bilirubin excess and brain deposition'),('Partial','Diagnostics','CH30S16','Coombs named; interpretation absent'),('Partial','Treatment/prevention','CH30S16','RhIG, phototherapy/exchange named; indications and thresholds absent')],
11:[('Direct','Definition','CH30S16','Bilirubin deposited in brain, potentially fatal')],
12:[('Direct','Pathophysiology/inheritance','CH30S18','X-linked recessive enzyme deficiency; oxidative damage and Heinz bodies'),('Direct','Manifestations/complications','CH30S19','Episodic hemolysis, jaundice, dark urine and pain'),('Missing','Diagnostics','','High-risk testing mentioned but assay/interpretation absent'),('Partial','Treatment','CH30S19','Transfusion listed; precise indications/trigger avoidance and iron indication missing')],
13:[('Direct','Pathophysiology/inheritance','CH30S22 CH30S23 CH30S24','HbS, recessive inheritance, stiffening/sickling triggers; amino-acid direction excluded'),('Direct','Manifestations/complications','CH30S26 CH30S27 CH30S28','Distinct crises, renal concentrating defect, infection, gallstones'),('Missing','Diagnostics','','No definitive testing pathway'),('Direct','Treatment categories','CH30S29','Crisis prevention, pain/infection care, fluids, hydroxyurea and hypoxia-qualified oxygen')],
14:[('Direct','Pathophysiology/inheritance','CH30S30 CH30S31','Recessive globin-production defects and alpha/beta forms'),('Direct','Manifestations/complications','CH30S32 CH30S33','Microcytic anemia, cardiovascular burden, hydrops'),('Missing','Diagnostics','','No complete assay and interpretation framework'),('Direct','Treatment categories','CH30S34','Transfusion, chelation, counseling, transplantation')],
15:[('Partial','Pathophysiology/inheritance','CH30S35 CH30S37 CH30S38N','A/B factor deficits, vWF defect, A recessive and vWD dominant; complete B/C inheritance missing'),('Direct','Manifestations','CH30S36 CH30S40','Factor bleeding versus immune platelet manifestations'),('Partial','Diagnostics','CH30S36','PT/PTT pattern; definitive testing absent'),('Partial','Treatment/complications','CH30S36 CH30S40','Factor replacement and ITP approaches; inhibitors and subtype complications missing')],
16:[('Direct','Pathophysiology/etiology','CH29S106','IgG against heparin–PF4'),('Partial','Manifestations/complications','CH29S106','Thrombocytopenia with thrombosis; full pattern absent'),('Missing','Diagnostics','','No timing, probability score or confirmatory assays'),('Partial','Treatment','CH29S106','Stop heparin stated; alternative regimen absent')],
17:[('Direct','Circulation/chambers/valves','CH31S11 CH31S15 CH31S16 CH31S17 CH31S18 CH31S22 CH31S23','Right/left oxygenation path and one-way valves'),('Direct','Cardiac cycle','CH31S20 CH31S21','Five phases and valve opening/closing'),('Partial','Pressures','CH31S19 CH31S45 CH31S46','Pressure-wave meanings/preload/afterload; numeric chamber pressures absent')],
18:[('Partial','ECG activity','CH31S29 CH31S30 CH31S31 CH31S32N','P, PR, QRS, ST, QT; complete T-wave and abnormal-tracing coverage absent')],
19:[('Partial','Coronary flow','CH31S25 CH31S26 CH31S27 CH31S28 CH31S71','Major branches/collaterals/drainage; full flow phases incomplete'),('Missing','Each artery occlusion territory','','No artery-by-territory mapping')],
20:[('Direct','Beta 1/2/3 catecholamine effects','CH31S35 CH31S36 CH31S37','Rate/force increases, beta2 coronary flow, beta3 negative inotropy')],
21:[('Direct','Pathophysiology/etiology','CH32S20 CH32S21 CH32S22 CH32S23 CH32S24 CH32S25','Output/resistance, primary/secondary causes and vascular remodeling'),('Partial','RAAS','CH31S68 CH32S24','Angiotensin/aldosterone effects; full cascade/feedback absent'),('Direct','Manifestations/diagnosis','CH32S26','Silent early disease and repeated measurement procedure'),('Direct','Treatment categories','CH32S27 CH32S28','Risk reduction and drug classes'),('Direct','Organ complications','CH32S20 CH32S25','MI, renal disease, stroke, encephalopathy')],
22:[('Direct','Pathophysiology/etiology','CH32S83 CH32S84','Delayed streptococcal immune response, M proteins, Aschoff bodies'),('Direct','Manifestations/complications','CH32S83 CH32S84 CH32S78','Carditis, arthritis, chorea/rash/nodules and valve disease'),('Missing','Diagnostics','','No formal diagnostic criteria/testing sequence'),('Partial','Treatment','CH32S84','Antibiotics/NSAIDs named; duration/risk-based prophylaxis incomplete')],
23:[('Direct','Pathophysiology/etiology','CH32S85','Endocardial injury, adherence and infected vegetations'),('Direct','Manifestations/complications','CH32S86','Fever/murmur, lesions, emboli and failure'),('Missing','Diagnostics','','No blood-culture/echo diagnostic criteria'),('Partial','Treatment','CH32S87','Weeks of antimicrobials and valve surgery; organism-specific regimens absent')],
24:[('Direct','Defect anatomy and flow','CH33S6 CH33S8 CH33S9 CH33S11 CH33S13 CH33S15 CH33S18 CH33S19 CH33S22 CH33S23 CH33S25 CH33S26 CH33S27','Shunts, obstructions, mixing and underdeveloped structures'),('Partial','Murmur type/location','CH33S7 CH33S10 CH33S16 CH33S18 U4-C33-Q01','PDA type and released VSD type/location; complete lesion matrix absent'),('Partial','Compensation','CH33S17N CH33S22 CH33S30 U4-C33-Q02','Squatting and hypertrophy supported; exact shunt-reversal claim gated, full compensation map absent')],
25:[('Direct','RBC function/life span','CH28S12','Oxygen carriage, deformability, 120 days adult'),('Direct','Platelet function/life span','CH28S23','Hemostasis, nondividing fragments, 8–11 days')],
26:[('Partial','Hemoglobin synthesis','CH28S40 CH28S41','Chains, heme/mitochondria and nutrients; full synthesis pathway missing, molecule count gated'),('Missing','Methemoglobin','','No supplied teaching beyond requested guide term')],
27:[('Direct','Granulocytes','CH28S13 CH28S14 CH28S15 CH28S16 CH28S17 CH28S18','Neutrophil/eosinophil/basophil and mast-cell roles'),('Direct','Agranulocytes','CH28S19 CH28S20 CH28S21','Lymphocytes, NK, monocytes/macrophages and dendritic functions')],
28:[('Direct','Production process','CH28S30 CH28S31 CH28S32 CH28S33 CH28S34 CH28S35 CH28S36','Stem cells, niches, proliferation/differentiation'),('Partial','Sites across fetal/neonatal/child/adult stages','CH30S6 CH28S30 CH28S35','Yolk/liver/marrow transition and adult locations; childhood site transition detail missing')],
29:[('Direct','Erythropoiesis','CH28S38 CH28S39','Hypoxia→renal EPO→marrow; reticulocytes'),('Partial','Iron cycle','CH28S44 CH28S45','Recycling, storage/transport proteins, hepcidin; absorption/export steps missing'),('Direct','Nutritional requirements','CH28S41 CH28S42 CH28S43N','Protein, B12/folate and listed supporting vitamins')],
30:[('Direct','Vessel/platelet/clotting mechanisms','CH28S49 CH28S50 CH28S51 CH28S52 CH28S53 CH28S56 CH28S57','Plug, coagulation, retraction'),('Direct','Regulation/fibrinolysis','CH28S59 CH28S60','Antithrombin, TFPI, C/S, plasmin'),('Partial','Clotting-factor synthesis vitamins','CH29S116','Vitamin K deficiency linked to coagulation; synthesis pathway/factor inventory absent')],
31:[('Direct','Splenic functions and splenectomy','CH28S26 CH28S27 CH28S44','Blood filtration/storage, fetal production, immunity and increased encapsulated infection risk')],
32:[('Direct','Lymph-node function','CH28S28 CH28S29','Lymph filtration and antigen processing'),('Partial','Inflammatory enlargement mechanism','CH29S85 CH29S86','Nearby lesion drainage and tender nodes; full cellular enlargement process absent')],
33:[('Partial','All anemia etiologies/pathophysiology','CH29S13 CH29S14 CH29S17 CH29S18 CH29S20 CH29S23 CH29S26 CH29S27 CH29S30 CH29S34 CH29S38 CH29S39 CH29S40','Major categories covered; complete sideroblastic/subtype mechanisms absent'),('Direct','Major clinical manifestations','CH29S16 CH29S21 CH29S24 CH29S28 CH29S35 CH29S41','Hypoxia and subtype clues at slide depth'),('Partial','Diagnostics/treatment/complications','CH29S22 CH29S29 CH29S32 CH29S35 CH29S36 CH29S41 CH29S42','Selected tests/approaches; exhaustive subtype algorithms absent'),('Missing','Complete compensatory responses','','No dedicated comprehensive physiologic compensation account')],
34:[('Direct','B12/folate mechanism','CH29S18 CH29S19 CH29S20 CH29S23','DNA/nuclear maturation failure with continuing RNA processes')],
35:[('Direct','Administration routes','CH29S22 U4-C29R-Q02','Injections or high oral doses; case absorption rationale'),('Missing','Evidence of effective B12 replacement','','No response criteria/timeline supplied')],
36:[('Direct','Pathophysiology/etiology','CH29S43 CH29S44 CH29S45 CH29S46','Relative volume loss versus absolute/PV/secondary excess'),('Direct','Manifestations/complications','CH29S47','Viscosity, pressure, thrombosis, pruritus, splenomegaly'),('Missing','Diagnostic work-up','','No complete work-up'),('Direct','Treatment categories','CH29S48','Phlebotomy and listed pharmacologic categories')],
37:[('Direct','Type I leukocyte changes','CH28S16 CH28S17 CH28S18 CH29S60 CH29S62','Eosinophil/basophil increase and mast-cell mediator release')],
38:[('Direct','Primary/secondary Raynaud and pathophysiology','CH32S42 CH32S46N','Episodic digital vasospasm; primary unknown origin versus secondary disease; mediator imbalance in notes')],
39:[('Direct','Varicose-vein development','CH32S12','Valve failure/obstruction/pump dysfunction→pooling/pressure/inflammation')],
40:[('Partial','Low-albumin consequences','CH28S9','Oncotic/carrier function only; full downstream fluid/transport consequences missing')]
}
guide_text=(PACKET/'Unit 4 Study Guide.txt').read_text()
pr={int(n):re.sub(r'\s+',' ',t).strip() for n,t in re.findall(r'(?:^|\n)\s*(\d+)\.\s+(.+?)(?=(?:\n\s*\d+\.)|\Z)',guide_text,re.S)}
components=[]
for n,rows in coverage_specs.items():
 comps=[]
 for j,(status,name,src,detail) in enumerate(rows,1):
  row={'id':f'U4-G{n:02d}-C{j:02d}','prompt':n,'component':name,'status':status,'sources':src.split(),'detail':detail};comps.append(row);components.append(row)
 ss=sorted(set(s for r in comps for s in r['sources']));ch=sorted(set(int(re.search(r'(?:CH|C)(\d+)',s)[1]) for s in ss))
 status='Direct' if all(r['status']=='Direct' for r in comps) else 'Missing' if all(r['status']=='Missing' for r in comps) else 'Partial'
 L['COVERAGE']['prompts'].append({'studyGuidePrompt':n,'promptVerbatim':pr[n],'status':status,'chapters':ch,'supported':' '.join(r['component']+': '+r['detail'] for r in comps if r['status']=='Direct'),'remainingGapOrLimit':' '.join(r['component']+': '+r['detail'] for r in comps if r['status']!='Direct'),'sources':[{'sourceId':s,'locator':s} for s in ss],'components':comps})
L['COVERAGE']['components']=components
(DOC/'coverage.json').write_text(json.dumps(L['COVERAGE'],indent=2))
(DOC/'COVERAGE.md').write_text('# Component-level coverage\n\nDirect means at supplied slide depth, not complete textbook coverage. Partial and missing components stay out of graded claims unless a narrower supported competency is explicitly mapped.\n\n| ID | Prompt/component | Status | Exact locators | Support or precise missing content |\n|---|---|---|---|---|\n'+'\n'.join(f'| {r["id"]} | {r["prompt"]}: {r["component"]} | {r["status"]} | {", ".join(r["sources"]) or "None"} | {r["detail"]} |' for r in components)+'\n')

# Released examples retain their original numbering and shared contexts. Original HTML
# and intake records stay in the private packet; only readable selected text is disclosed.
def group_blocks(blocks):
 pre=[];groups={};cur=None
 for b in blocks:
  txt=b.get('text','')
  match=re.search(r'Question\s+(\d+)',txt) if b['tag'].startswith('H') else None
  if match:cur=int(match[1]);groups[cur]=[];continue
  rows=[f'{j}. {x}' for j,x in enumerate(b.get('items',[]),b.get('start') or 1)] if b['tag'] in ['OL','UL'] else [txt]
  (pre if cur is None else groups[cur]).extend(x for x in rows if x)
 return '\n\n'.join(pre),{k:'\n\n'.join(v) for k,v in groups.items()}
case_text={}
for entry in index['entries']:
 folder=PACKET/entry['folder'];data=json.loads((folder/'case-study-source.json').read_text());ch=json.loads((folder/'manifest.json').read_text())['chapter']
 suffix='29R' if ch==29 and 'Erythrocyte' in entry['folder'] else '29L' if ch==29 else str(ch)
 pre,q=group_blocks(data['questions']['blocks']);apre,a=group_blocks(data['answers']['blocks'])
 for n,question in q.items():
  sid=f'U4-C{suffix}-Q{n:02d}';original=a.get(n,'No answer supplied.');case_text[sid]=original
  model=original;adjudication='Supplied answer retained for self-comparison; no automatic grade or mastery.'
  if ch==31 and n==2:
   model='Editorial adjudication: Sinus node, choice 2 in the question. The original answer label says “4. Sinus node”; its text identifies the supported structure but its number is wrong. Chapter 31 slide 29 supports sinus-node initiation. The original explanation is truncated; its missing ending has not been reconstructed.'
   adjudication=model
  if ch==33:
   if n==1:model='Editorial adjudication: VSD; the supplied first answer supports a left-to-right shunt, without immediate cyanosis. Its final cyanosis passage belongs with the next TOF question and is excluded here. Precise later shunt reversal criteria remain unsupported. Sources: Chapter 33 slides 9–10.'
   if n==2:model='Editorial adjudication: squatting gives compensatory relief during TOF hypoxic spells (Chapter 33 slide 17 speaker notes). The supplied labels are shifted; the squatting explanation appears under answer 3. The claimed obligatory reversal to left-to-right flow is not used as a scored rule.'
   if n==3:model='Editorial adjudication: the cyanotic-defect list appears under supplied answer 4. Use the individual anatomy in Chapter 33 slides 22–27: TOF, tricuspid atresia, transposition, anomalous pulmonary venous connection and truncus. Complete lesion-specific oxygenation and compensation criteria need the textbook.'
   if n==4:model='Editorial explanation from slides, not an original supplied answer: tricuspid atresia is an imperforate tricuspid valve with no normal right-atrial/right-ventricular communication. Chapter 33 slides 23–24 describe the associated shunt pathways. The captured answer set has no correctly labeled tricuspid-atresia answer.'
   adjudication=model
  csrefs=[sid]+(['CH33S17N'] if ch==33 and n==2 else [f'CH31S29'] if ch==31 and n==2 else [f'CH33S{v}' for v in ({1:[9,10],2:[17],3:[22,23,25,26,27],4:[23,24]}[n])] if ch==33 else [])
  concept=next(k for k,c in L['CONCEPTS'].items() if c['sec']==f'ch{ch}')
  item={'id':sid.lower(),'rootId':sid.lower(),'c':concept,'sec':f'ch{ch}','dom':'blood' if ch<31 else 'cardiac','t':'teach','q':question,'model':model,'rubric':[model],'s':csrefs,'tier':1,'pool':'released','eligible':False,'explain':model,'provenance':f'Released course-selected {suffix} example {n}. Original record preserved privately. Authorship/recurrence unverified.'}
  L['CASES'].append({'id':'case-'+sid.lower(),'title':f'Chapter {suffix} · released example {n}','dom':item['dom'],'stem':pre or f'Chapter {suffix} course-selected example {n}.','src':csrefs,'items':[item],'scopeNote':adjudication})
  L['SOURCES'][sid]={'t':f'Chapter {suffix} released question/answer {n}','f':'#sources/'+sid,'tier':1,'short':sid,'provenance':'Selected text from released course page; original private intake retained, not instructor-authorship evidence.'}
  # Original source record is disclosed independently from editorial adjudication.
  L['SOURCE_HTML'][sid]='<h3>Shared case context</h3><p class="longtext">'+E(pre)+'</p><h3>Released question</h3><p class="longtext">'+E(question)+'</p><h3>Original supplied answer record</h3><p class="longtext">'+E(original)+'</p><h3>Editorial disposition</h3><p>'+E(adjudication)+'</p>'

# Stable IDs carry decisions, not cosmetic scenario wording. Authored key is position 0
# in the authoring records; storage rotation is deterministic and runtime shuffling
# preserves the indexed option identities in the accepted engine.
for file,pool in [('practice.txt','practice'),('mocks.txt','mock')]:
 for line in (DOC/'authoring'/file).read_text().splitlines():
  if not line.strip():continue
  v=line.split('|');assert len(v)==(7 if pool=='practice' else 8),line
  if pool=='mock':form,ch,key,decision,ss,stem,choices,rationales=v
  else:ch,key,decision,ss,stem,choices,rationales=v;form=''
  ch=int(ch);opts=choices.split('~');why=rationales.split('~');assert len(opts)==len(why)==4
  ident=f'u4-{("m"+form) if form else "p"}-c{ch}-{decision}'
  options=[{'t':t,'w':w,'ok':j==0} for j,(t,w) in enumerate(zip(opts,why))]
  rot=int(hashlib.sha256(ident.encode()).hexdigest()[:2],16)%4;options=options[rot:]+options[:rot]
  excerpt='\n\n'.join(s+' — '+(slides.get(s) or notes.get(s) or case_text.get(s) or 'UNAVAILABLE') for s in ss.split());assert 'UNAVAILABLE' not in excerpt,ident
  it={'id':ident,'rootId':ident,'c':f'u4-c{ch}-{key}','sec':f'ch{ch}','dom':'blood' if ch<31 else 'cardiac','t':'mc','q':stem,'o':options,'s':ss.split(),'tier':1,'pool':pool,'eligible':True,'explain':why[0],'decision':decision,'evidenceExcerpt':excerpt,'editorialRevision':'u4-personal-2026-10-02-r2','dnaRevision':'u4-personal-2026-10-01-r1','reviewer':'Codex root, separate personal editorial and source passes'}
  assert it['c'] in L['CONCEPTS'];L['ITEMS'].append(it)
  if form:L['FORMS'][form].append(ident)
counts={status:sum(c['status']==status for c in components) for status in ['Direct','Partial','Missing']};L['COVERAGE']['componentCounts']=counts
needed=set(s for i in L['ITEMS'] for s in i['s'])|set(s for a in L['GUIDE'].values() for c in a for s in c['src'])|set(s for c in components for s in c['sources'])|set(s for c in L['CASES'] for i in c['items'] for s in i['s'])
for sid in sorted(needed):
 if sid in L['SOURCES']:continue
 txt=slides.get(sid) or notes.get(sid);assert txt,sid
 m=re.match(r'CH(\d+)S(\d+)(N?)',sid);ch,n,note=m.groups()
 L['SOURCES'][sid]={'t':f'Chapter {ch}, slide {n}'+(' speaker notes' if note else ''),'f':'#sources/'+sid,'tier':1,'short':sid,'provenance':'Exact selected supplied slide text'+('; note-to-slide relationship verified from original PPTX' if note else '')+'. Source wording may contain documented errors; exclusions are in the coverage map.'}
 L['SOURCE_HTML'][sid]='<p class="longtext">'+E(txt)+'</p>'
# Supplemental teaching comparisons complete the supported component detail.
def supplement(ch,key,title,nums,paragraphs,rows=None):
 body=''.join('<p>'+E(t)+'</p>' for t in paragraphs)
 if rows:body+='<table><thead><tr><th>Compare</th><th>Packet-supported mechanism or finding</th></tr></thead><tbody>'+''.join('<tr><th>'+E(a)+'</th><td>'+E(b)+'</td></tr>' for a,b in rows)+'</tbody></table>'
 L['GUIDE'][f'ch{ch}'].append({'id':f'u4-g{ch}-detail-{key}','h':title,'html':body,'c':[],'src':refs(ch,nums),'tier':1})
 for sid in refs(ch,nums):
  if sid not in L['SOURCES']:
   L['SOURCES'][sid]={'t':f'Chapter {ch}, slide '+sid.split('S')[1],'f':'#sources/'+sid,'tier':1,'short':sid,'provenance':'Selected supplied slide text; no additional textbook claim.'};L['SOURCE_HTML'][sid]='<p class="longtext">'+E(slides[sid])+'</p>'
supplement(28,'development','Developmental trends, without invented reference intervals',[63,64,65,66],['The supplied trends are age dependent. They support comparison, but do not establish complete numeric CBC normal/abnormal ranges.'],[('RBCs/reticulocytes','Birth levels are high; neonatal RBC survival is shorter than adult survival.'),('Neutrophils','High at birth, rising in the first days; fall within/below adult range after two weeks; adult level by about four years in the supplied account.'),('Eosinophils/monocytes','High during the first year; monocytes then decrease to adult levels.'),('Platelets','Full-term neonatal counts are comparable to adult counts and remain so through childhood.')])
supplement(29,'anemia-management','Compare production, loss and destruction',[13,16,27,29,30,31,32,34,35,36,38,39,40,41,42],['General anemia management addresses the cause plus the supported need for blood, vitamins or iron. The packet names categories; it does not provide a complete treatment algorithm.'],[('Iron deficiency','Low iron availability from intake, absorption or loss; microcytic/hypochromic cells, possible spoon nails, ferritin assessment. Replace iron and identify/eliminate bleeding.'),('Inflammatory anemia','Iron can be abundant in total stores but poorly available. Lactoferrin/apoferritin compete for iron; renal EPO and marrow response may fail. Treat the underlying disease.'),('Aplastic anemia','Pancytopenia and fatty hypocellular marrow; exposures/autoimmunity or DNA-repair defects may contribute. Blood/marrow evaluation; transplant or listed immunosuppression.'),('PNH','CD55/CD59 deficiency permits complement-mediated intravascular lysis; hemoglobinuria, abdominal pain and thrombosis are listed. Eculizumab is named.'),('Autoimmune hemolysis','Antibodies target RBC surface antigens. Warm/cold types use optimal antibody-binding temperature; cold agglutinins are IgM. Remove cause/treat disease; corticosteroids, splenectomy/rituximab are listed by line.'),('Drug-related immune hemolysis','The hapten model involves a reaction against foreign antigens; specific drugs are listed. Do not generalize their supplied percentages to every drug or population.')])
supplement(31,'pressure-coronary','Pressure waves and coronary connections',[19,25,26,27,28,31,45,47],['The a wave marks atrial contraction; the v wave marks atrial filling. The slide links the c wave to mitral bulging into the left atrium, x descent to ejection and y descent to right-ventricular filling. These are source descriptions, without numeric chamber-pressure reference ranges.','The RCA list includes conus, right marginal and posterior descending branches. The LCA list includes LAD and circumflex. Collaterals connect branches; capillaries exchange nutrients. Coronary venous drainage includes the coronary sinus, great cardiac vein and posterior vein of the left ventricle. The sinus drains to the right atrium. The full occlusion-territory map remains missing.','QT represents ventricular electrical systole and generally shortens as heart rate rises. Frank-Starling links filling/stretch with force within the physiologic range; excessive stretch can reduce output. Do not redefine afterload as filling.'])
supplement(33,'defect-comparison','Compare the defect before interpreting a murmur',[6,7,8,9,10,11,13,14,15,16,18,19,20,21,22,23,24,25,26,27],['The flow classification distinguishes increased pulmonary flow, decreased pulmonary flow, obstruction without shunting and mixing. A murmur in the slide does not supply an absent auscultatory location. Complete compensation and murmur-location maps remain gaps.'],[('PDA','Persistent ductal connection; continuous machinery murmur. Direction conflicts within the packet and is excluded from scored rules.'),('ASD','Atrial communication with supplied left-to-right flow; may be asymptomatic. Primum, secundum and sinus-venosus types; surgical closure is listed.'),('VSD','Ventricular communication; left-to-right shunt. Burden varies with defect size, age and pulmonary resistance; HF, growth difficulty, murmur/thrill. Catheter or patch approaches are listed.'),('AV canal','Endocardial cushion nonfusion affects atrial/ventricular septa and AV valves. Murmur, HF and respiratory infections; repair is listed.'),('Coarctation','Aortic narrowing; newborn deterioration with duct closure. Older children: arm hypertension, weak leg pulses, cool skin and exercise cramps. Support, prostaglandin and surgery are listed.'),('Aortic stenosis','Malformed/fused cusps narrow LV outflow. May be silent or cause exercise intolerance, syncope or chest/epigastric pain. Valvotomy/commissurotomy/Ross options are named.'),('Pulmonary stenosis','Thickened leaflets narrow RV outflow; severe atresia. Dyspnea, fatigue, thrill/cyanosis or HF may occur. Observe mild disease; balloon/valvotomy listed for severe disease.'),('Hypoplastic left heart','Underdeveloped LV/aorta/arch with mitral atresia/stenosis. Duct closure reduces systemic perfusion and can cause hypoxemia, acidosis and shock; staged repair is listed.'),('TOF','VSD, overriding aorta, pulmonary stenosis, RV hypertrophy. Cyanosis, hypoxic spells, clubbing/feeding difficulty; squatting relieves spells, repair addresses anatomy.'),('Tricuspid atresia','No RA–RV communication, with associated septal defects and RV underdevelopment. Cyanosis, growth failure, dyspnea and later polycythemia/clubbing. Prostaglandin, shunts/septostomy and banding are listed.'),('Transposition','Reversed great-artery origins make parallel circuits; communication is required for survival. Cyanosis may worsen during day one; arterial switch is listed.'),('TAPVC','Pulmonary veins connect directly/indirectly to the right side. Obstructed and unobstructed forms differ; surgical reconnection to LA and ASD closure are listed.'),('Truncus','The embryonic arterial outlet fails to separate; the common trunk straddles a VSD. Types vary by pulmonary-artery origin. Do not import unsupported subtype prognosis.')])
# 25 distinct supported practice decisions spanning all chapters.
boss=[]
for ch,n in [(28,4),(29,7),(30,5),(31,3),(32,3),(33,3)]:
 pool=[x for x in L['ITEMS'] if x['pool']=='practice' and x['sec']==f'ch{ch}'];boss.extend(x['id'] for x in pool[:n])
L['BOSSES']=[{'id':'u4-boss','title':'Unit 4 Boss Drill','blurb':'25 supported original decisions across six chapters.','pass':0.8,'refs':boss}]
sha=hashlib.sha256(json.dumps(L['ITEMS'],sort_keys=True).encode()).hexdigest();L['BANK_SHA256']=sha;L['CONTENT_REVISION']='bank-'+sha[:16]
for it in L['ITEMS']:it['contentRevision']=L['CONTENT_REVISION']
OUT.mkdir(parents=True,exist_ok=True);(OUT/'js/data').mkdir(parents=True,exist_ok=True)
(OUT/'js/data/course.js').write_text('(function(root){var L=root.L=root.L||{};Object.assign(L,'+json.dumps(L,ensure_ascii=False,separators=(',',':'))+');L.srcBase=function(s){return L.SOURCES[s]?s:null;};L.srcLabel=function(s){return (L.SOURCES[s]||{}).t||s;};})(typeof window!=="undefined"?window:globalThis);\n')
(DOC/'authoring/bank.json').write_text(json.dumps(L['ITEMS'],ensure_ascii=False,indent=2))
(DOC/'coverage.json').write_text(json.dumps(L['COVERAGE'],indent=2))
print('Original items:',len(L['ITEMS']),'Practice:',sum(i['pool']=='practice' for i in L['ITEMS']),'Forms:',{f:len(v) for f,v in L['FORMS'].items()},'Cases:',len(L['CASES']),'Concepts:',len(L['CONCEPTS']),'Components:',counts)
print('Bank:',sha)
